### PR TITLE
fix: custom debug function not processing all args

### LINKED ISSUE #13364: Custom debug function missing last method argument
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x.x

### Node.js version

18.x

### MongoDB server version

5

### Typescript version (if applicable)

5

### Issue
https://github.com/Automattic/mongoose/blob/aaacf466bb0ad633c7e9b497458045a6e5c12558/lib/drivers/node-mongodb-native/collection.js#L212
Logging with custom log function missing last argument due to incorrect slicing index.

### Potential fix
Clone array with `args.slice(0, args.length)`

### Risk
- May require existing code to add redact action on large objects such as `session` which happen to be in last argument

### Steps to Reproduce

```
import { connect } from 'mongoose';
import * as util from 'util';

(async () => {
  const MONGO_CONNECTION_STRING = 'mongodb://localhost:27017/db?&directConnection=true';
  const mongoose = await connect(MONGO_CONNECTION_STRING);

  mongoose.set('debug', (collectionName, methodName, ...methodArgs) => {
    console.log(`${collectionName}.${methodName}(${util.inspect(methodArgs).slice(2, -2)})`);
  });

  const collection = mongoose.connection.collection('Test');
  await collection.findOne({ key: 'value' });

  await mongoose.connection.close();
})();
```

### Expected Behavior
Expect: print `Test.findOne({ key: 'value' })`
Actual: print `Test.findOne()`

### PR DESCRIPTION
**Pull request by IslandRhythms**
closes #13364 

Had to fix a couple of tests because of the changes. Let me know if that is not the correct approach.

### CODE REVIEW

File: lib/drivers/node-mongodb-native/collection.js [hunk 1]
```diff
@@ -208,8 +208,14 @@ function iter(i) {
 
     if (debug) {
       if (typeof debug === 'function') {
+        let range = '';
```
Comment (vkarpov15) [inline lib/drivers/node-mongodb-native/collection.js:211]: Please stop initializing values that aren't strings to empty strings. If you want to add a placeholder value, do `let range = null`

**Review by vkarpov15 — APPROVED** [review]

**Comment by forivall** [comment]
I see this happening on 6.x - could this be backported? (shall I open a PR?)

**Comment by vkarpov15** [comment]
@forivall sure, if you're able to open a PR that would be great.
