### PR TITLE
fix(model): handle document array paths set to non-array values in Model.castObject()

### LINKED ISSUE #15075: Mongoose 8.x: Discriminator schema validation breaks in static validation
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.3 (also observed in 8.0.0)

### Node.js version

20.17.0

### MongoDB server version

7.0.15

### Typescript version (if applicable)

_No response_

### Description

There are significant inconsistencies in validation behavior between instance validation (`new Model().validate()`) and static validation (`Model.validate()`) when using discriminator schemas with nested document arrays:

#### Instance Validation
- Circle: Passes validation ✓
- Square: Fails validation as expected ✓

#### Static Validation
- Circle: Fails validation with "radius is required" ✗
- Square: Passes validation unexpectedly ✗

### Regression?
This issue appears to have changed in behavior between Mongoose versions:
- Mongoose 6.13.5: Both instance and static validation work consistently
- Mongoose 7.8.3: Both instance and static validation work consistently
- Mongoose 8.0.0: Inconsistent validation behavior emerges
- Mongoose 8.8.3: Inconsistent validation behavior persists

### Steps to Reproduce

```javascript
const mongoose = require('mongoose');

// Interfaces (conceptual, for TypeScript-like clarity)
// interface Circle { kind: 'Circle'; radius: number; }
// interface PropertyPath { property: string; path: string; }
// interface Square { kind: 'Square'; propertyPaths: PropertyPath[]; }

async function runValidationTest() {
    // Create the base shape schema
    const shapeSchema = new mongoose.Schema({ name: String }, {
        discriminatorKey: 'kind',
        _id: false
    });

    // Main schema with shape array
    const schema = new mongoose.Schema({
        shape: [shapeSchema]
    });

    // Circle discriminator
    schema
        .path('shape')
        .discriminator('Circle', new mongoose.Schema({
            radius: {
                type: mongoose.Schema.Types.Number,
                required: true
            }
        }, { _id: false }));

    // PropertyPath schema for Square
    const propertyPathSchema = new mongoose.Schema({
        property: {
            type: mongoose.Schema.Types.String,
            required: true,
        },
        path: {
            type: mongoose.Schema.Types.String,
            required: true,
        }
    }, { _id: false });

    // Square discriminator
    schema
        .path('shape')
        .discriminator(
            'Square',
            new mongoose.Schema({
                propertyPaths: {
                    type: [propertyPathSchema],
                    required: true
                }
            }, { _id: false })
        );

    // Create the model
    const Model = mongoose.model('ShapeTest', schema);

    // Test cases
    const circle = { shape: [{ kind: 'Circle', radius: 5 }] };
    const square = { shape: [{ kind: 'Square', propertyPaths: [{}] }] };

    console.log("--- Instance Validation (new Model().validate()) ---");

    // Circle instance validation
    try {
        await new Model(circle).validate();
        console.log("Circle instance validation: PASSED ✓");
    } catch (error) {
        console.error("Circle instance validation: FAILED ✗", error);
    }

    // Square instance validation
    try {
        await new Model(square).validate();
        console.error("Square instance validation: UNEXPECTEDLY PASSED ✗");
    } catch (error) {
        console.log("Square instance validation: FAILED AS EXPECTED ✓");
        console.log("Validation Error:", error.message);
    }

    console.log("\n--- Static Validation (Model.validate()) ---");

    // Circle static validation
    try {
        await Model.validate(circle);
        console.log("Circle static validation: PASSED ✓");
    } catch (error) {
        console.error("Circle static validation: FAILED ✗", error);
    }

    // Square static validation
    try {
        await Model.validate(square);
        console.error("Square static validation: UNEXPECTEDLY PASSED ✗");
    } catch (error) {
        console.log("Square static validation: FAILED AS EXPECTED ✓");
        console.log("Validation Error:", error.message);
    }
}

// Run the test
runValidationTest().catch(console.error);
```

### Expected Behavior

Both `new Model().validate()` and `Model.validate()` should:
1. Successfully validate circle documents with a radius
2. Fail validation for square documents missing required `propertyPaths` properties

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #15075

**Summary**

#15075 pointed out that `Model.castObject()` silently ignores document arrays that are set to primitive non-null values. This PR fixes that, including accounting for `castNonArrays` schema object.

**Examples**

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -3687,6 +3688,19 @@ Model.castObject = function castObject(obj, options) {
     }
 
     if (schemaType.$isMongooseDocumentArray) {
+      const castNonArraysOption = schemaType.options.castNonArrays != null ? schemaType.options.castNonArrays : schemaType.constructor.options.castNonArrays;
```
Comment (BenaliDjamel) [inline lib/model.js:3691]: Isn't this shorter and better (if castNonArrays can be null or undefined). 
```suggestion
      const castNonArraysOption = schemaType.options?.castNonArrays ??schemaType.constructor.options.castNonArrays;
```

**Review by hasezoey — COMMENTED** [review]
LGTM
