### PR TITLE
fix: Update ChangeStream hydration condition

### LINKED ISSUE #12169: In v6.5.0 mongoose.disconnect() causing Cannot read properties of undefined (reading 'fullDocument')
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5

### Node.js version

16.15

### MongoDB server version

mongo:5 from official Docker repo

### Description

I have a unit test that was working fine in v6.4.7.  In 6.5.0 change stream throws an exception when `mongoose.disconnect()` is called at the of the test.

`data` is undefined here
https://github.com/Automattic/mongoose/blob/6.5/lib/cursor/ChangeStream.js#L57

```
Home/git/openbeta/openbeta-graphql/node_modules/mongodb/lib/utils.js:419
                    throw error;
                    ^

TypeError: Cannot read properties of undefined (reading 'fullDocument')
    at ChangeStream.<anonymous> (/Home/git/openbeta/openbeta-graphql/node_modules/mongoose/lib/cursor/ChangeStream.js:57:22)
    at ChangeStream.emit (node:events:539:35)
    at ChangeStreamCursor.<anonymous> (/Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/change_stream.ts:817:46)
    at ChangeStreamCursor.emit (node:events:527:28)
    at /Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/cursor/abstract_cursor.ts:823:18
    at /Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/utils.ts:535:5
    at completeEndSession (/Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/sessions.ts:283:9)
    at /Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/sessions.ts:297:7
    at maybePromise (/Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/utils.ts:520:3)
    at ClientSession.endSession (/Home/git/openbeta/openbeta-graphql/node_modules/mongodb/src/sessions.ts:258:24)
e


```

### Steps to Reproduce

**Important**: Test requires a replica set.

```javascript
await mongoose.connect(
      `mongodb://${user}:${pass}@${server}/testdb?authSource=admin&readPreference=primary&ssl=false&replicaSet=${rsName}`,
      { autoIndex: false }
    )

const changeStream = mongoose.connection.watch(pipeline, { fullDocument: 'updateLookup' })
const stream = changeStream.on('change', change => {
    console.log(change)
  })

await stream.close() // not helping
await mongoose.disconnect() 

```

### Expected Behavior

No undefined exception like in v6.4.7

### PR DESCRIPTION
**Pull request by ramos-ph**
**Summary**

There is an issue when using a `ChangeStream` in a replica set, you'll get an `undefined` error when you try to call `mongoose.disconnect()`:

```js
await mongoose.connect(`mongodb://${host}:${port}/?replicaSet=${rset}`, {
  autoIndex: false,
});

const changeStream = mongoose.connection.watch(pipeline, {
  fullDocument: "updateLookup",
});
const stream = changeStream.on("change", (change) => {
  console.log(change);
});

await stream.close();
await mongoose.disconnect(); // `data.fullDocument` is undefined
```

The issue was introduced in one of the commits from versions 6.4.7 to 6.5.0, as stated in #12169. This PR fixes this by correctly addressing where the options are coming from.

**Examples**

Here's the result for the current version:
image

Here's the result for the fix:
image

Closes #12169

### CODE REVIEW

File: lib/cursor/ChangeStream.js [hunk 1]
```diff
@@ -54,8 +54,8 @@ class ChangeStream extends EventEmitter {
 
         ['close', 'change', 'end', 'error'].forEach(ev => {
           this.driverChangeStream.on(ev, data => {
-            if (data.fullDocument != null && this.options && this.options.hydrate) {
-              data.fullDocument = this.options.model.hydrate(data.fullDocument);
+            if (this.options && this.options.fullDocument != null && this.options.hydrate) {
+              data.fullDocument = this.options.model.hydrate(this.options.fullDocument);
```
Comment (vkarpov15) [inline lib/cursor/ChangeStream.js:58]: This is very wrong. The whole point here is to hydrate `data.fullDocument`, if it exists. `this.options.fullDocument` is a boolean, not the document to hydrate.

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
Why not just add `if (data != null && data.fullDocument != null && ...)` ?

File: lib/cursor/ChangeStream.js (hunk 1 above)
Comment (ramos-ph) [reply lib/cursor/ChangeStream.js]: Ah, my bad. I misinterpreted the intent code 😅 
Just fixed it! Still working the same.
Thanks!

**Comment by vnugent** [comment]
Hi, 
when do you think we have this released?
I did a quick test.  The issue still exists in 6.5.1

upgrading mongoose

```javascript
-    "mongoose": "6.4.7",
+    "mongoose": "6.5.1",
```

**Review by vkarpov15 — APPROVED** [review]
I think this was also fixed in #12224, but we'll merge this one as well. Will ship a release with the fix within 24 hours :+1:
