### PR TITLE
types: add UpdateQueryKnownOnly type for stricter UpdateQuery type checking

### LINKED ISSUE #13630: Definition of type `UpdateQuery` is not very accurate cause code hint not work
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x

### Node.js version

18.x

### MongoDB server version

4.x

### Typescript version (if applicable)

4.x

### Description

The definition of type `UpdateQuery` is not very accurate cause code hint not work. 

### Steps to Reproduce

The definition of types `UpdateQuery` for now:
```typescript
export type UpdateQuery<T> = _UpdateQuery<T> & AnyObject;
```

Typescript can not do code hint  with using it, when you add some field not  belong to this schema. Like this: 
```typescript
// schema
interface SchemaDemo {
  field_1: string;
  field_2: string;
}

function update(doc: UpdateQuery<SchemaDemo>) {}

update({ test_field: 'test' }); // Will not get types error
```
`update({ test_field: 'test' })` It should get a types error, because `test_field` is not a field of interface `SchemaDemo`. Types `UpdateQuery` is an intersection type which include `AnyObject`, so `test_field` matched `AnyObject`.  In a sense, ` UpdateQuery` make no senses for now.

### Expected Behavior

Don't use `AnyObject`, it make type system not work. If user want to do something about custom type, just use generic type to do that.  I think `UpdateQuery` should by defined like that: 
```typescript
export UpdateQuery<TSchema = AnyObject>  = _UpdateQuery<TSchema>  & Partial<TSchema>
```

In this design, more flexibility for users. Usage case:
```typescript
type UpdateQuery<TSchema = AnyObject>  = _UpdateQuery<TSchema>  & Partial<TSchema>

// schema
interface SchemaDemo {
  field_1: string;
  field_2: string;
}

function update(doc: UpdateQuery<SchemaDemo>) {}

update({ field_test: 1 }); //  ❌ no fields
update({ field_1: 2}); // ❌ get erro type is not matched
update({ field_1: '' }); //  ✅
update({ $set: { field_1: '' }}); ✅

function update2(doc: UpdateQuery) {}

update2({  aaa: 1 }); // ✅  used as any 
```
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #13630

**Summary**

#13630 points out that there's no good way right now to enforce a more strict update syntax if you prefer to only allow known top-level keys in updates. This PR adds a separate `UpdateQueryKnownOnly` utility type for that. I'm not entirely convinced that this is useful or necessary, but it could be helpful in some cases. What do you think @hasezoey ?

**Examples**

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -618,6 +618,16 @@ declare module 'mongoose' {
...
 
+  /**
+   * A more strict form of UpdateQuery that enforces updating only
+   * known top-level properties.
+   * @example
+   * ```js
+   * { age: 30 }
+   * ```
+   */
+  export type UpdateQueryKnownOnly<T> = _UpdateQuery<T, {}>;
```
Comment (hasezoey) [inline types/index.d.ts:629]: it would probably good to have a example of how this type is meant to be used.

is it meant to be used like `.find({} as UpdateQueryKnownOnly<IUser>)` or `.find<UpdateQueryKnownOnly<IUser>({})` or a completely different way?

**Review by hasezoey — APPROVED** [review]
looks good to me for those that want stricter queries in types, though a example of how to apply the new type would be good

**Review by AbdelrahmanHafez — APPROVED** [review]
Nice! Would like to see more of stricter TS for filters/queries.
Can be challenging to apply for dot-separated paths though, but that's a good start!

File: types/index.d.ts (hunk 1 above)
Comment (vkarpov15) [reply types/index.d.ts:629]: More along the lines of this:

```ts
function updateUser(update: UpdateQueryKnownOnly<IUser>) {
  return User.updateOne({}, update);
}
```

Use `UpdateQueryKnownOnly` for extra strictness in params and definitions when you want it. Does that make sense?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez dot-separated paths is something we're unlikely to support in the foreseeable future. The MongoDB Node driver recently removed support for that because it caused a lot of problems; performance issues, and no way to stop infinite recursion in case of self-referential types. Unfortunately a limitation that we're gonna have to live with for now.

File: types/index.d.ts (hunk 1 above)
Comment (hasezoey) [reply types/index.d.ts:631]: so if no conditions are given via parameters and are "inline", the following should be used, right?
`User.updateOne({}, { something: 1 } as UpdateQueryKnownOnly<IUser>)`
