### PR TITLE
fix: avoid applying map property getters when saving

### LINKED ISSUE #13657: Map schema type converts UUID into plain string
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

18

### MongoDB server version

4.4

### Typescript version (if applicable)

_No response_

### Description

Seems Map schema type makes unnecessary conversion via `__schemaType.applyGetters` for updates query. I noted it when developing my custom types that based on MongooseBuffer, i just tried  Map + UUID combination and got the same issue.

### Steps to Reproduce

```js
import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';

const Schema = new mongoose.Schema(
  {
    doc_map: {
      type: mongoose.Schema.Types.Map,
      of: mongoose.Schema.Types.UUID,
    },
  },
  { collection: 'users_test' },
);

const User = mongoose.model('TestUser', Schema);

async function test() {
  const user = new User({
    doc_map: new Map([
      ['role_1', randomUUID()],
      ['role_2', randomUUID()],
    ]),
  });

  await user.save();

  // all good here
  console.log(user.doc_map);

  // trying to update
  user.doc_map.set('role_1', randomUUID());

  await user.save();

  // got string in doc_map -> role_1
}

test().catch(console.error);

```

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #13657

**Summary**

Right now, `save()` will actually apply getters on map paths when updating an existing doc. That's why the test case from #13657 shows maps of uuids getting saved as strings. This PR fixes that by making it so that `getValue()`, Mongoose's internal way to "get dotted path without Mongoose internals", always passes `getters: false` to `map.get()`.

**Examples**

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -630,9 +630,23 @@ function _populateObj(obj) {
...
 };
 
+/*!
+ * ignore
+ */
+
+const mapGetterOptions = Object.freeze({ getters: false });
+
+function getValueLookup(obj, part) {
+  const _from = obj && obj._doc ? obj._doc : obj;
```
Comment (AbdelrahmanHafez) [inline lib/utils.js:643]: Nitpick:
```suggestion
  const _from = obj?._doc || obj;
```

**Review by AbdelrahmanHafez — APPROVED** [review]
One minor suggestion, otherwise LGTM. Thanks 👍

**Review by hasezoey — APPROVED** [review]

File: lib/utils.js [hunk 2]
```diff
@@ -630,9 +630,23 @@ function _populateObj(obj) {
...
+  obj = _from instanceof Map ?
+    _from.get(part, mapGetterOptions) :
+    _from[part];
+  return obj;
```
Comment (Uzlopak) [inline lib/utils.js:647]: Is there a reason for reassigning it?

```suggestion
  return _from instanceof Map ?
    _from.get(part, mapGetterOptions) :
    _from[part];
```

**Review by Uzlopak — APPROVED** [review]
LGTM

File: lib/utils.js (hunk 1 above)
Comment (vkarpov15) [reply lib/utils.js:643]: Works for me, we do have one place where we use `?.` in runtime code and no complaints so far. So this should work nicely.
