### PR TITLE
Fix findByIdAndUpdate behavior with undefined id

### LINKED ISSUE #10964: findByIdAndUpdate should not work with undefined id
**Do you want to request a *feature* or report a *bug*?**
Neither a feature or a bug, but an improvement for the API

**What is the current behavior?**
Actually, findByIdAndUpdate(id, ...) is equivalent to findOneAndUpdate({ _id: id }, ...), as stated by the documentation.
That's working accordingly, however this is not the logically expected behavior when the id is undefined:
`findOneAndUpdate({ _id: undefined }, ...)` => this form, understandably, should update the first entry.
`findByIdAndUpdate(undefined, ...)` => this form however should fail.

**What is the expected behavior?**
I expect an argument error when using `findByIdAndUpdate` with an undefined id.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose v5.13.8

### PR DESCRIPTION
**Pull request by gramliu**
**Summary**

findByIdAndUpdate should not work with an undefined id, if an update is specified. Resolves #10964

**Examples**

I added a test to demonstrate this change.

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -2676,6 +2680,9 @@ Model.findByIdAndUpdate = function(id, update, options, callback) {
       throw new TypeError(msg);
     }
     return this.findOneAndUpdate({ _id: id }, undefined);
+  } else if (id === undefined) {
+    const msg = 'Model.findByIdAndUpdate(): id cannot be undefined if update is specified.\n';
```
Comment (vkarpov15) [inline lib/model.js:2684]: Why `\n`?

File: lib/model.js [hunk 2]
```diff
@@ -2676,6 +2680,9 @@ Model.findByIdAndUpdate = function(id, update, options, callback) {
       throw new TypeError(msg);
     }
     return this.findOneAndUpdate({ _id: id }, undefined);
+  } else if (id === undefined) {
```
Comment (vkarpov15) [inline lib/model.js:2683]: Our tests rely on `Model.findByIdAndUpdate()` with no arguments working, so can we make this `else if (arguments.length > 0 && id === undefined)`?

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
I think this PR is helpful, but causes some test failures. We can merge this when those get sorted out

File: lib/model.js (hunk 1 above)
Comment (gramliu) [reply lib/model.js]: Oh, I was just following the format of the preceding error messages. I went ahead and removed it

File: lib/model.js (hunk 2 above)
Comment (gramliu) [reply lib/model.js]: Thank you for bringing this up. I forgot to consider that. I went ahead and added this to the condition

**Comment by gramliu** [comment]
@vkarpov15 I pushed some changes that might resolve the failing tests. For the function itself, I added the check for undefined id only if the length of arguments was greater than 1. Moreover, I updated the test I wrote to properly check that the error is thrown. It turns out that my original test was wrong

**Review by vkarpov15 — APPROVED** [review]
Needed to patch up the tests but LGTM overall :+1:

**Comment by vkarpov15** [comment]
Unfortunately I have to revert this change - it is backwards breaking as indicated in #11149. We'll consider this for our next major release.
