### PR TITLE
fix: setting global `strictQuery` after Schema creation wasn't working

### LINKED ISSUE #12703: Setting global strictQuery doesn't work after schemas are created
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.x

### MongoDB server version

6.x

### Typescript version (if applicable)

4.8.0

### Description

```mongoose.set('strictQuery', false);``` only correctly disables strict query behavior if you run it before the schemas are created.  After the schemas are created, changes to this property is ignored.  Similarly, if you change it in the middle of schema creation, it affects some schemas but not others.  The schemas should respect the current state of this global if it's set, not what it was at schema creation time.

### Steps to Reproduce

```#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gh7008', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  title: String,
});

const Test = mongoose.model('test', schema);

mongoose.set('strictQuery', false);

const test0 = new Test({
  title: 'chimichanga'
});
const test1 = new Test({
  title: 'burrito bowl'
});
const test2 = new Test({
  title: 'taco supreme'
});

async function run() {
  assert.strictEqual(mongoose.version, '6.7.2');
  await conn.dropDatabase();
  await test0.save();
  await test1.save();
  await test2.save();

  let cond = {
    $or: [
      {
        title: {
          $regex: 'urri',
          $options: 'i'
        }
      },
      {
        name: {
          $regex: 'urri',
          $options: 'i'
        }
      }
    ]
  }
  let found = await Test.find(cond);
  assert.strictEqual(found.length, 1);
  assert.strictEqual(found[0].title, 'burrito bowl');

  console.log('All Assertions Pass.');
  return conn.close();
}

run();
```

### Expected Behavior

The current state of ```mongoose.set('strictQuery', false);``` should be used if no per-query/schema overrides are specified.

### PR DESCRIPTION
**Pull request by lpizzinidev**
fix #12703

### CODE REVIEW

File: lib/cast.js [hunk 1]
```diff
@@ -387,5 +387,18 @@ function getStrictQuery(queryOptions, schemaUserProvidedOptions, schemaOptions)
   if ('strict' in schemaUserProvidedOptions) {
     return schemaUserProvidedOptions.strict;
   }
+  if (
+    context.mongooseCollection &&
+    context.mongooseCollection.conn &&
+    context.mongooseCollection.conn.base &&
+    context.mongooseCollection.conn.base.options) {
+    const mongooseOptions = context.mongooseCollection.conn.base.options;
```
Comment (Uzlopak) [inline lib/cast.js:395]: I guess you can simplify this
```javascript
const mongooseOptions = context.mongooseCollection &&
    context.mongooseCollection.conn &&
    context.mongooseCollection.conn.base &&
    context.mongooseCollection.conn.base.options;

if (mongooseOptions) {
    if ('strictQuery' in mongooseOptions) {
      return mongooseOptions.strictQuery;
    }
    if ('strict' in mongooseOptions) {
      return mongooseOptions.strict;
    }
}
```

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:
