### PR TITLE
fix(types): add HydratedDocumentFromSchema to make it easier to pull inferred hydrated doc type

### LINKED ISSUE #12319: Get Document type with QueryHelpers and InstanceMethods
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.2

### Node.js version

17.3

### MongoDB version

5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

How can I get infered Document type in typescript? So I could use it as argument type in DTO or enywhere else. For example I have this:
```ts
const projectSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
  },
  {
    methods: {
      async doSomething() {
        // ...
      },
    },
  }
);

const ProjectModel = mongoose.model('Project', projectSchema);
```
Basically, I want a return type of `await ProjectModel.findOne()`. Closest I got is:
```ts
export type ProjectDocument = mongoose.HydratedDocument<
  mongoose.InferSchemaType<typeof projectSchema>,
  mongoose.ObtainSchemaGeneric<typeof projectSchema, 'TQueryHelpers'>,
  mongoose.ObtainSchemaGeneric<typeof projectSchema, 'TInstanceMethods'>
>;
```
But it looks bulky. Is there another way?

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #12319

**Summary**

#12319 correctly pointed out that it is clunky to pull the hydrated document type from an inferred schema. This PR adds a helper `HydratedDocumentFromSchema` that helps make that cleaner.

**Examples**

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -118,6 +118,12 @@ declare module 'mongoose' {
 
   export type HydratedDocument<DocType, TMethodsAndOverrides = {}, TVirtuals = {}> = DocType extends Document ? Require_id<DocType> : (Document<unknown, any, DocType> & Require_id<DocType> & TVirtuals & TMethodsAndOverrides);
 
+  export type HydratedDocumentFromSchema<TSchema extends Schema> = HydratedDocument<
```
Comment (hasezoey) [inline types/index.d.ts:121]: maybe consider adding a comment describing what this type is meant to be for (and how to properly use it)?
