### PR TITLE
fix: make `doValidate()` on document array elements run validation on the whole subdoc

### LINKED ISSUE #11770: Make `$__reset()` not mark paths as `init`
**Do you want to request a *feature* or report a *bug*?**

Potential bug/issue

**What is the current behavior?**

It is very strange that `$__reset()`, which should reset a document to a "nothing modified" state, relies on marking subdocuments as `init`. This popped up in #11672, and this behavior may be hiding other bugs. No concrete issues right now, more of a note to self to investigate further.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #11770

**Summary**

In #11770 I made a note that we leave subdocuments in `init` state after `save()` to work around some issues like #6818. That is technically incorrect, because `init` should only be used for paths that are loaded from the database. The underlying issue comes down to the fact that array subdocument paths' `doValidate()` function doesn't run validation on paths in the document.

In this PR, I made it so that the embedded schema type in document arrays have a `doValidate()` that is the same as `SubdocumentPath`'s. In order to support this change, needed to fix a couple of places where we relied on the old behavior in update validators and `Model.validate()`.

Future work: make array subdocument paths a separate class, and make primitive arrays also validate all their subpaths when calling `doValidate()`.

We should probably put this change in 6.4, or hold off until after 6.4 It is a fairly sizable change of Mongoose internals, and while our tests do all pass, I'd like to be cautious with this one.

**Examples**

### CODE REVIEW

File: lib/document.js [hunk 1]
```diff
@@ -2505,6 +2505,14 @@ function _getPathsToValidate(doc) {
       continue;
     }
 
+    if (_pathType.$isMongooseDocumentArray) {
+      for (const p of paths) {
+        if (p === null || p.startsWith(_pathType.path + '.')) {
```
Comment (AbdelrahmanHafez) [inline lib/document.js:2510]: Is strict equality in `p === null` intended, or did you mean `p == null`?

**Comment by AbdelrahmanHafez** [comment]
LGTM, thanks. 👍

Frankly, I've always found it difficult to tell the difference between Subdocument, embedded documents, and arrays of documents.
If we were to design mongoose with the knowledge we have today, is there a way we can have logic apply to all cases?

**Review by AbdelrahmanHafez — APPROVED** [review]

File: lib/document.js (hunk 1 above)
Comment (Uzlopak) [reply lib/document.js:2510]: In ine 2487 we also have strill null check

File: lib/helpers/updateValidators.js [hunk 2]
```diff
@@ -125,26 +125,20 @@ module.exports = function(query, schema, castedDoc, options, callback) {
...
+                for (const key of Object.keys(err.errors)) {
+                  const _err = err.errors[key];
+                  _err.path = updates[i] + '.' + key;
+                  validationErrors.push(_err);
+                }
+              } else {
+                err.path = updates[i];
+                validationErrors.push(err);
+              }
               return callback(null);
```
Comment (Uzlopak) [inline lib/helpers/updateValidators.js:138]: I guess we can remove this line, as we anyway go to line 141?

**Review by Uzlopak — CHANGES_REQUESTED** [review]
can we have some tests please :)?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez we did some work to consolidate array subdocuments and single nested subdocuments for 6.0. Now, `ArraySubdocument` extends from `Subdocument`. Bringing nested paths into that mix would be very tricky, because nested paths are by design not subdocuments.
