### PR TITLE
fix(aggregate): added `await` to prevent exception in aggregate exec

### LINKED ISSUE #13125: TypeError: cursor.toArray is not a function
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.0

### Node.js version

16.17.1

### MongoDB server version

6.0.4 (offline)

### Typescript version (if applicable)

_No response_

### Description

If I run my application and keep the database offline, I can crash the application by running an aggregation due to a typo in `lib/aggregate.js`. Stack trace:
```
node_modules/mongoose/lib/aggregate.js:1054
    result = await cursor.toArray();
                          ^

TypeError: cursor.toArray is not a function
    at Aggregate.exec (node_modules/mongoose/lib/aggregate.js:1054:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (web/routes/index.js:4:19)
```

When I navigate to the code it's complaining about, the issue seems to be that `await cursor.toArray();` should be `(await cursor).toArray();` in the `exec` function:
```
try {
  const cursor = collection.aggregate(this._pipeline, options);
  result = await cursor.toArray();
} catch (error) {
...
```

### Steps to Reproduce

Simply run an aggregation using `.exec()` while the database connection has not been established.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by lpizzinidev**
closes #13125

### CODE REVIEW

**Comment by wfjake** [comment]
I was able to test this fix in my project and confirmed that I no longer get a TypeError, just the expected timeout. Thanks for the good work!

File: lib/aggregate.js [hunk 1]
```diff
@@ -1050,7 +1050,7 @@ Aggregate.prototype.exec = async function exec() {
   let result;
   try {
     const cursor = collection.aggregate(this._pipeline, options);
-    result = await cursor.toArray();
+    result = await (await cursor).toArray();
```
Comment (Uzlopak) [inline lib/aggregate.js:1053]: Actually very unsexy. But it is what it is.

File: test/aggregate.test.js [hunk 2]
```diff
@@ -1242,4 +1242,16 @@ describe('aggregate: ', function() {
     });
   });
 
+  it('should not throw error if database connection has not been established (gh-13125)', async function() {
+    const m = new mongoose.Mongoose();
+    const mySchema = new Schema({ test: String });
+    const M = m.model('Test', mySchema);
+
+    const aggregate = M.aggregate();
+    aggregate.match({ $text: { $search: 'test' } });
```
Comment (vkarpov15) [inline test/aggregate.test.js:1251]: Probably best to not use text search because that requires a special index

File: test/aggregate.test.js [hunk 3]
```diff
@@ -1242,4 +1242,16 @@ describe('aggregate: ', function() {
...
+
+    assert.doesNotThrow(async function() {
+      await aggregate.exec();
```
Comment (vkarpov15) [inline test/aggregate.test.js:1254]: I suspect this will cause some issues because this operation will eventually time out because of buffering. Probably best to save the promise and then await on it later, for example `const promise = aggregate.exec(); await m.connect(start.uri); const res = await promise;` similar to https://github.com/Automattic/mongoose/blob/c4fd23d64087510d3293f7168b06c284abf52a3c/test/collection.test.js#L37

File: lib/aggregate.js (hunk 1 above)
Comment (vkarpov15) [reply lib/aggregate.js:1053]: I'd prefer `await cursorPromise.then(cursor => cursor.toArray())`

**Review by vkarpov15 — CHANGES_REQUESTED** [review]

File: test/aggregate.test.js (hunk 3 above)
Comment (hasezoey) [reply test/aggregate.test.js:1254]: or like in other parts of the tests, use [`await assert.rejects`](https://nodejs.org/api/assert.html#assertrejectsasyncfn-error-message)

File: lib/aggregate.js [hunk 4]
```diff
@@ -1050,7 +1050,7 @@ Aggregate.prototype.exec = async function exec() {
   let result;
   try {
     const cursor = collection.aggregate(this._pipeline, options);
```
Comment (AbdelrahmanHafez) [inline lib/aggregate.js:1052]: Why not just add an `await` here? Am I missing something?
```suggestion
    const cursor = await collection.aggregate(this._pipeline, options);
```

File: lib/aggregate.js [hunk 5]
```diff
@@ -1049,7 +1049,7 @@ Aggregate.prototype.exec = async function exec() {
   const options = clone(this.options || {});
   let result;
   try {
-    const cursor = collection.aggregate(this._pipeline, options);
+    const cursor = await collection.aggregate(this._pipeline, options);
```
Comment (vkarpov15) [inline lib/aggregate.js:1052]: It looks like this still throws a `MongoNotConnectedError: Client must be connected before running operations`. I'll merge this PR into master so I can more easily debug.

**Review by vkarpov15 — APPROVED** [review]
