### PR TITLE
fix(populate): make `refPath` work as a function

### LINKED ISSUE #16028: `ValidationError: CastError: TypeError: path.split is not a function` with `refPath` as a function
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

9.2.1

### Node.js version

25.4.0

### MongoDB server version

not relevant

### Typescript version (if applicable)

5.9.3

### Description

Trying to use `refPath` with a function and assign a document to that property in `create`, it results in a undescriptive `ValidationError`:
```txt
ValidationError: RefPathTest validation failed: ref: Cast to ObjectId failed for value "{
  propA: 'helloA',
  _id: new ObjectId('699069acf888d8b513312cd9'),
  __v: 0
}" (type model) at path "ref" because of "TypeError"
```

Upon further investigation, this is caused by a `TypeError` inside mongoose:
```txt
reason: TypeError: path.split is not a function
    at Schema.hasMixedParent (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/schema.js:1944:25)
    at Schema.path (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/schema.js:1288:23)
    at model.Document.$__path (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:2034:25)
    at model.Document.get (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1943:65)
    at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1435:29
    at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1437:7)
    at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1170:16)
    at model.Document (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:181:12)
    at model.Model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:131:12)
    at new model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:4805:15)
    at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2747:20
    at Array.map (<anonymous>)
    at model.create (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2735:34)
    at Object.<anonymous> (/mnt/ssd/projects/nodejs/typegoose/test/tests/ref.test.ts:484:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5),
```

I had also tried with other property names in case they were messing with "special properties", but the error remained the same.

Finally, note that assigning a document to a `refPath` property that is not a function works as expected (where it gets cast to the reftype, in this case `ObjectId`)

<details>
<summary>Full Error</summary>

```txt
ValidationError: RefPathTest validation failed: ref: Cast to ObjectId failed for value "{
  propA: 'helloA',
  _id: new ObjectId('699069acf888d8b513312cd9'),
  __v: 0
}" (type model) at path "ref" because of "TypeError"
    at model.Document.invalidate (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:3405:32)
    at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1522:12)
    at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1170:16)
    at model.Document (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:181:12)
    at model.Model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:131:12)
    at new model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:4805:15)
    at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2747:20
    at Array.map (<anonymous>)
    at model.create (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2735:34)
    at Object.<anonymous> (/mnt/ssd/projects/nodejs/typegoose/test/tests/ref.test.ts:484:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5) {
  errors: {
    ref: CastError: Cast to ObjectId failed for value "{
      propA: 'helloA',
      _id: new ObjectId('699069acf888d8b513312cd9'),
      __v: 0
    }" (type model) at path "ref" because of "TypeError"
        at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1523:9)
        at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1170:16)
        at model.Document (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:181:12)
        at model.Model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:131:12)
        at new model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:4805:15)
        at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2747:20
        at Array.map (<anonymous>)
        at model.create (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2735:34)
        at Object.<anonymous> (/mnt/ssd/projects/nodejs/typegoose/test/tests/ref.test.ts:484:40)
        at processTicksAndRejections (node:internal/process/task_queues:104:5) {
      stringValue: '"{\n' +
        "  propA: 'helloA',\n" +
        "  _id: new ObjectId('699069acf888d8b513312cd9'),\n" +
        '  __v: 0\n' +
        '}"',
      messageFormat: undefined,
      kind: 'ObjectId',
      value: [Object],
      path: 'ref',
      reason: TypeError: path.split is not a function
          at Schema.hasMixedParent (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/schema.js:1944:25)
          at Schema.path (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/schema.js:1288:23)
          at model.Document.$__path (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:2034:25)
          at model.Document.get (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1943:65)
          at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1435:29
          at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1437:7)
          at model.$set (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:1170:16)
          at model.Document (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/document.js:181:12)
          at model.Model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:131:12)
          at new model (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:4805:15)
          at /mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2747:20
          at Array.map (<anonymous>)
          at model.create (/mnt/ssd/projects/nodejs/typegoose/node_modules/mongoose/lib/model.js:2735:34)
          at Object.<anonymous> (/mnt/ssd/projects/nodejs/typegoose/test/tests/ref.test.ts:484:40)
          at processTicksAndRejections (node:internal/process/task_queues:104:5),
      valueType: 'model'
    }
  },
  _message: 'RefPathTest validation failed'
}

```

</details>

### Steps to Reproduce

```ts
const childASchema = new Schema({ propA: { required: true, type: String } });
const childBSchema = new Schema({ propB: { required: true, type: String } });
const ChildAModel = mongoose.model('ChildA', childASchema);
const ChildBModel = mongoose.model('ChildB', childBSchema);

const indexes = [ChildAModel.modelName, ChildBModel.modelName];

const refPathTestSchema = new mongoose.Schema({
  model: { required: true, min: 0, max: 1, type: Number },
  ref: {
    refPath: function () {
      return indexes[this.model];
    },
    type: mongoose.Types.ObjectId,
  },
});
const RefPathTestModel = mongoose.model('RefPathTest', refPathTestSchema);

const childAdoc = await ChildAModel.create({ propA: 'helloA' });
await ChildBModel.create({ propB: 'helloB' });

try {
  const doc = await RefPathTestModel.create({ model: 0, ref: childAdoc } as any);
} catch (err) {
  // necessary, as otherwise you dont get the actual error printed
  console.error(err);
  throw err;
}
```

### Expected Behavior

No error, or a more descriptive error on what went wrong.

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
Fixes #16028
Re #6669 #8452 #8469 #8731

While working on `refPath` as a function, I found two behavior gaps:

1. In document assignment/casting (`$set` / `create`), function `refPath` was not handled correctly for the "assign a document to an ObjectId ref" flow, leading to confusing cast errors (for example, `path.split is not a function` wrapped in `CastError`).
2. In populate, function `refPath` was called with `options.path` (for example `notifications.target`) instead of an indexed path per subdoc (for example `notifications.0.target`).

That mismatch meant array subdocs could not reliably resolve per-element model paths, and `$set` vs populate could disagree.

What this PR changes:

- Unifies function `refPath` call semantics across assignment/casting and populate.
- Keeps the established design from https://github.com/Automattic/mongoose/issues/8469#issuecomment-881940298:
  - `this` is the subdocument/document currently being processed.
  - returned `refPath` is interpreted as root-relative.
- For array subdocs, passes root-relative indexed `path` to function `refPath` (for example `notifications.0.target`, `channels.1.notifications.0.target`).
- Uses the same indexed `path` format in both `$set` and populate flows.
- Throws `MongooseError` (instead of leaking `TypeError`) when function `refPath` returns a non-string.
- Preserves discriminator behavior by normalizing numeric segments only for internal discriminator schema traversal (not for user-facing `path` passed to `refPath`).

I chose to always use indexed paths because assignment/casting needs a concrete element path to resolve the correct model for that exact subdocument.
If populate uses an unindexed path while `$set` uses indexed resolution, behavior diverges.
Using indexed root-relative paths everywhere gives one consistent contract and ensures function `refPath` computes the same result in both flows.
This passes all the current tests since the existing tests relied on regex replacements like `path.replace(/\.item$/, '.kind');`

Given how broken `refPath` currently is, I think it's safe to introduce this change in a minor version

I tested this feature extensively with different scenarios: 
- top-level docs
- subdoc arrays
- deeply nested arrays
- lean()
- doc.populate()
- shared schema reused across multiple arrays
- single nested subdocs
- parity of path argument between $set and populate
- explicit non-string function refPath error handling in both assignment and populate.

Additionally, I updated `populate` docs to clarify function `refPath` contract, root-relative indexed `path` behavior, and the array-subdocument pattern.

In particular, for array subdocs, static string `refPath` like `items.targetModel` is insufficient when per-element resolution is needed. The recommended pattern is function `refPath`, for example:

```js
refPath: function(doc, path) {
  return path.replace(/\.target$/, '.targetModel');
}
```

### CODE REVIEW

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 1]
```diff
@@ -17,6 +17,9 @@ const modelSymbol = require('../symbols').modelSymbol;
 const populateModelSymbol = require('../symbols').populateModelSymbol;
 const schemaMixedSymbol = require('../../schema/symbols').schemaMixedSymbol;
 const StrictPopulate = require('../../error/strictPopulate');
+const numericPathSegmentPattern = '\\.\\d+(?=\\.|$)';
```
Comment (hasezoey) [inline lib/helpers/populate/getModelsMapForPopulate.js:20]: Maybe there should be a empty line in between (as the first part are just imports)

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 2]
```diff
@@ -361,6 +347,151 @@ module.exports = function getModelsMapForPopulate(model, docs, options) {
...
+                item.indexedPathPrefix + '.' + key;
+              next.push({ subdoc: value, indexedPathPrefix: valuePath });
+            }
+          }
+          continue;
+        }
+
+        if (source != null && typeof source === 'object') {
+          for (const key of Object.keys(source)) {
+            const value = source[key];
```
Comment (hasezoey) [inline lib/helpers/populate/getModelsMapForPopulate.js]: Is this faster than just using `Object.entries()`?

File: test/document.test.js [hunk 3]
```diff
@@ -3178,6 +3179,218 @@ describe('document', function() {
...
+          const { User, ActivityLog } = createTestContext({ refPath: 'targetModel' });
+          const user = await User.create({ name: 'Hafez' });
+
+          // Act
+          const activityLog = await ActivityLog.create({ targetModel: 'User', targetUser: user });
+          const activityLogFromDb = await ActivityLog.findById(activityLog._id).populate('targetUser');
+
+          // Assert
+          assert.equal(activityLogFromDb.targetUser.name, 'Hafez');
+        });
```
Comment (hasezoey) [inline test/document.test.js:3246]: If this is the baseline, shouldnt it be ordered before the other tests?

File: lib/document.js [hunk 4]
```diff
@@ -1428,11 +1428,25 @@ Document.prototype.$set = function $set(path, val, type, options) {
...
 
       // Check refPath
-      const refPath = schema.options.refPath;
+      let refPath = schema.options.refPath;
       if (refPath == null) {
         return false;
       }
-      const modelName = val.get(refPath);
+
+      if (typeof refPath === 'function' && !refPath[modelSymbol]) {
```
Comment (vkarpov15) [inline lib/document.js:1436]: What's the reason for this refPath[modelSymbol] check here?

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 5]
```diff
@@ -361,6 +347,151 @@ module.exports = function getModelsMapForPopulate(model, docs, options) {
...
+ * @param {Object} queryProjection
+ * @returns {{modelNames: String[], refPath: String|null}}
+ * @private
+ */
+function _getModelNamesFromFunctionRefPath(refPath, doc, schema, populatePath, modelSchema, queryProjection) {
+  const modelNames = [];
+  let normalizedRefPath = null;
+  const schemaPath = schema?.path;
+
+  if (schemaPath != null && populatePath.endsWith('.' + schemaPath)) {
```
Comment (vkarpov15) [inline lib/helpers/populate/getModelsMapForPopulate.js]: For performance reasons, we should avoid using `startsWith()` and `endsWith()`, in favor of `charAt()` and `slice()`

Image

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 6]
```diff
@@ -361,6 +347,151 @@ module.exports = function getModelsMapForPopulate(model, docs, options) {
   }
 };
 
+/**
+ * Resolve model names for function-style `refPath` and return the first
+ * resolved refPath value so discriminator handling can inspect it later.
+ *
+ * @param {Function} refPath
+ * @param {Document|Object} doc
+ * @param {SchemaType} schema
```
Comment (vkarpov15) [inline lib/helpers/populate/getModelsMapForPopulate.js:357]: Going forward, we should make sure we do not name SchemaType variables `schema`, that is confusing since a Schema is a distinct class. I know this is far from the only place where we use `schema` to refer to a SchemaType, but I would like to change that going forward.

**Review by vkarpov15 — APPROVED** [review]
I made a couple of minor improvements, mostly perf related, but LGTM overall thanks.

Reading through this PR made me just want to get rid of `refPath()` function support though - we added that in #6683 but I find the `refPath()` function API to be inferior to `ref()` function, which we added even earlier (at least #6554) . WDYT?
