### PR TITLE
fix(document): avoid using childSchemas.path for compatibility with pre-Mongoose-8.8 schemas

### LINKED ISSUE #15071: Update from 8.8.2 to 8.8.3 causes "Uncaught TypeError: Invalid `path`. Must be either string or array"
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.3

### Node.js version

20.18.0

### MongoDB server version

7

### Typescript version (if applicable)

_No response_

### Description

I tried upgrading Mongoose from 8.8.2 to 8.8.3. But when trying to create a document I got this issue:

```
Uncaught TypeError: Invalid `path`. Must be either string or array
      at Object.exports.get (node_modules/mpath/lib/index.js:59:11)
      at Object.exports.getValue (Role node_modules/mongoose/lib/utils.js:624:16)
      at model.Document.$__getValue (Role node_modules/mongoose/lib/document.js:1771:16)
      at getSubdocs (Role node_modules/mongoose/lib/document.js:3695:23)
      at model.Document.$getAllSubdocs (Role node_modules/mongoose/lib/document.js:3723:3)
      at _getPathsToValidate (Role node_modules/mongoose/lib/document.js:2714:25)
      at model.Document.$__validate (Role node_modules/mongoose/lib/document.js:2980:25)
      at node_modules/kareem/index.js:497:25
      at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Tried to look a little bit and it seems that the problematic line is `for (const { path } of doc.$__schema.childSchemas) {`
It seems my schema has a `paths` property but not a `path` property and hence an `undefined` value is passed down. But that's where my knowledge ends. Cannot say how come.

### Steps to Reproduce

Sorry but I cannot paste hundreds of lines of company code in here. I have no idea where in my schema the problem is.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #15071

**Summary**

#15071 is a tricky situation where the user has a shared connection package that uses Mongoose 8.8, and a client npm package which defines schemas using Mongoose 8.5 but then defines models using the Mongoose 8.8 connection. And we added a new `childSchemas.path` property in 8.8.3 with #15029 that Mongoose 8.8.3 expects, but schemas from Mongoose 8.5 do not have.

The "right" solution is to tell the user to ensure a consistent version of Mongoose, because we cannot realistically test that schemas from every version of Mongoose work with models from every other version of Mongoose. However, in the interest of not breaking code that previously worked, we can use this PR's more backwards-compatible approach.

**Examples**

### CODE REVIEW

**Review by AbdelrahmanHafez — APPROVED** [review]
LGTM 👍

File: lib/document.js [hunk 1]
```diff
@@ -3703,8 +3703,10 @@ Document.prototype.$getAllSubdocs = function(options) {
   const subDocs = [];
   function getSubdocs(doc) {
     const newSubdocs = [];
-    for (const { path } of doc.$__schema.childSchemas) {
-      const val = doc.$__getValue(path);
+
+    for (const { model } of doc.$__schema.childSchemas) {
+      // Avoid using `childSchemas.path` to avoid compatibility versions with pre-8.8 versions of Mongoose
+      const val = doc.$__getValue(model.path);
```
Comment (hasezoey) [inline lib/document.js:3709]: Should this workaround be reverted for the next major version?
If it should, maybe consider adding a TODO or some other kind of reminder.

File: lib/utils.js [hunk 2]
```diff
@@ -631,6 +631,9 @@ exports.getValue = function(path, obj, map) {
 const mapGetterOptions = Object.freeze({ getters: false });
 
 function getValueLookup(obj, part) {
+  if (part === '$*' && obj instanceof Map) {
+    return obj;
+  }
```
Comment (hasezoey) [inline lib/utils.js:636]: Maybe this should get a test?

**Review by hasezoey — APPROVED** [review]

File: lib/document.js (hunk 1 above)
Comment (vkarpov15) [reply lib/document.js:3709]: I don't see any reason to prioritize removing this workaround, unless the extra logic in `getValue()` for handling maps causes issues.

File: lib/utils.js (hunk 2 above)
Comment (vkarpov15) [reply lib/utils.js:636]: This code is covered by the tests added in the PR, albeit indirectly.
