### PR TITLE
fix(getModelMapForPopulate): mention model name in error

### LINKED ISSUE #13406: Mention model name in missing virtual option in `getModelsMapForPopulate`
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently the error below does not mention the model name, and the stacktrace  is all just `node_modules/mongoose`, making it hard to find which model is causing a problem
https://github.com/Automattic/mongoose/blob/c1c3dfe5c8ee77383b61df4bceab2f59fd5bab17/lib/helpers/populate/getModelsMapForPopulate.js#L392

example:
```txt
/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:392
      return new MongooseError('If you are populating a virtual, you must set the ' +
             ^

MongooseError: If you are populating a virtual, you must set the localField and foreignField options
    at _virtualPopulate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:392:14)
    at getModelsMapForPopulate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:42:12)
    at populate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/model.js:4186:21)
    at _populate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/model.js:4146:5)
    at /mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/model.js:4118:5
    at new Promise (<anonymous>)
    at Function.populate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/model.js:4117:10)
    at /mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/query.js:2465:11
    at /mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/query.js:3080:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### PR DESCRIPTION
**Pull request by hasezoey**
**Summary**

This PR adds the model name to a error, it is probably not the best method for debugging which model the problem is, but better than not mentioning it.
also adds a test-file for the the helper because i was unsure where to add the test

fixes #13406

### CODE REVIEW

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 1]
```diff
@@ -390,7 +390,7 @@ function _virtualPopulate(model, docs, options, _virtualRes) {
 
     if (!localField || !foreignField) {
       return new MongooseError('If you are populating a virtual, you must set the ' +
-        'localField and foreignField options');
+        'localField and foreignField options' + ` (Model: ${model.modelName})`);
```
Comment (Uzlopak) [inline lib/helpers/populate/getModelsMapForPopulate.js:393]: looks correct but could be probably 

```suggestion
        `localField and foreignField options (Model: ${model.modelName})`);
```

But does not make a big difference.

File: lib/helpers/populate/getModelsMapForPopulate.js [hunk 2]
```diff
@@ -390,7 +390,7 @@ function _virtualPopulate(model, docs, options, _virtualRes) {
 
     if (!localField || !foreignField) {
       return new MongooseError('If you are populating a virtual, you must set the ' +
-        'localField and foreignField options');
+        `localField and foreignField options (Model: ${model.modelName})`);
```
Comment (AbdelrahmanHafez) [inline lib/helpers/populate/getModelsMapForPopulate.js:393]: Nitpick:
Wrapping fields in backticks makes it clear that this an exact identifier that people should be looking for, not just part of the message.
```suggestion
        `\`localField\`, and \`foreignField\` options for model: \`${model.modelName}\``);
```

**Review by AbdelrahmanHafez — APPROVED** [review]
One minor nitpick, but otherwise LGTM. Thanks! 👍

File: test/helpers/getModelsMapForPopulate.test.js [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+      virtuals: {
+        someVirtual: {}
+      }
+    });
+
+    const model = db.model('Test', sch);
+
+    const doc = await model.create({ test: new mongoose.Types.ObjectId() });
+
+    await assert.rejects(() => model.findById(doc._id).populate('someVirtual').exec(), /If you are populating a virtual, you must set the localField and foreignField options \(Model: Test\)/);
```
Comment (vkarpov15) [inline test/helpers/getModelsMapForPopulate.test.js:39]: I think it would be more helpful to also include the virtual path in case the user is populating multiple paths. Maybe something more like `"Mongoose can't populate virtual ${virtual.path} on model ${model} because it doesn't have a localField or foreignField set"` ?

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
Minor comment, but decent idea overall

File: lib/helpers/populate/getModelsMapForPopulate.js (hunk 2 above)
Comment (hasezoey) [reply lib/helpers/populate/getModelsMapForPopulate.js:393]: good idea, maybe we should note it down somewhere and change all errors to use this style consistently

File: test/helpers/getModelsMapForPopulate.test.js (hunk 3 above)
Comment (hasezoey) [reply test/helpers/getModelsMapForPopulate.test.js]: is 66c553042def63af1d96c45b9ac5e183b8f6d1e2 better?

**Review by vkarpov15 — APPROVED** [review]

File: lib/helpers/populate/getModelsMapForPopulate.js (hunk 2 above)
Comment (AbdelrahmanHafez) [reply lib/helpers/populate/getModelsMapForPopulate.js]: Thanks 👍
