### PR TITLE
fix(model+document): avoid depopulating manually populated doc as getter value

### LINKED ISSUE #14759: Manually populated documents get saved as strings instead of `ObjectId`s in combination with SchemaType getter
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.1

### Node.js version

20.15.1

### MongoDB server version

7.0.12

### Typescript version (if applicable)

_No response_

### Description

I use a SchemaType getter on `ObjectId` because I think strings are more convenient to work with than ObjectIds.
Their use is described and mentioned here:
 * https://mongoosejs.com/docs/api/schematype.html#SchemaType.prototype.get()
 * https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters
 * https://github.com/Automattic/mongoose/issues/6996#issuecomment-434063799
 
Have a look at the code snippet below. I cannot query for a pet anymore, given its owner.

I think that is because `pet.save()` unexpectedly saved the owner id as a string into the mongoDB instead of an `ObjectId`.

image

### Steps to Reproduce

```js
/**
 * I want to globally work with strings instead of ObjectIds
 * because that allows me to reuse my underlying types
 * across server and client.
 *
 * Also see:
 * https://mongoosejs.com/docs/api/schematype.html#SchemaType.prototype.get()
 * https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters
 * https://github.com/Automattic/mongoose/issues/6996#issuecomment-434063799
 */
mongoose.Schema.ObjectId.get(
  value => {
    if (value?.constructor?.name?.toLowerCase() === 'objectid') return String(value)
    return value
  }
)

const ownerSchema = new mongoose.Schema({ name: 'String' })
const petSchema = new mongoose.Schema({
  name: 'String',
  owner: { type: 'ObjectId', ref: 'owner' }
})

const Owner = mongoose.model('owner', ownerSchema)
const Pet = mongoose.model('pet', petSchema)

const owner = new Owner({ name: 'Alice' })
const pet = new Pet({ name: 'Kitty', owner: owner })

await owner.save()
// pet.owner = pet.owner._id // Manually depopulating it like this makes the whole thing work
await pet.save()

/**
 * The property 'owner' of 'pet' has unexpectedly been saved
 * as a string into the mongoDB instead of ObjectId.
 * 
 * No matter how I query for it, mongoose is not
 * able to find it...
 */

const reloadAttempts = await Promise.all([
  Pet.findOne({ owner: owner }),
  Pet.findOne({ owner: owner._id }),
  Pet.findOne({ owner: String(owner._id) }),
  Pet.findOne({ owner: new mongoose.Types.ObjectId(owner._id) }),
])

console.log(reloadAttempts) // Logs [ null, null, null, null ] but shouldn't
```

### Expected Behavior

I expect my `reloadAttempts` to not be all `null`.

Also the ObjectId getter should not change the mongoDB data structure.

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #14759

**Summary**

When depopulating, it looks like Mongoose applies `_id` getters, which is problematic if you add a default getter to convert all ObjectIds to strings like here: https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters. Fixed by replacing `doc._id` with `doc._doc._id` to get the raw id and bypass any getters.

We should backport this to 7.x and 6.x. Same issue impacts those versions.

**Examples**

### CODE REVIEW

File: lib/document.js [hunk 1]
```diff
@@ -1394,7 +1394,7 @@ Document.prototype.$set = function $set(path, val, type, options) {
 
     let didPopulate = false;
     if (refMatches && val instanceof Document && (!val.$__.wasPopulated || utils.deepEqual(val.$__.wasPopulated.value, val._id))) {
```
Comment (fardolieri) [inline lib/document.js:1396]: Not completely sure, but did you miss the `_doc` in the `deepEqual` check?

```diff
-    if (refMatches && val instanceof Document && (!val.$__.wasPopulated || utils.deepEqual(val.$__.wasPopulated.value, val._id))) {
+    if (refMatches && val instanceof Document && (!val.$__.wasPopulated || utils.deepEqual(val.$__.wasPopulated.value, val._doc._id))) {
```

Comment (fardolieri) [reply lib/document.js:1396]: Otherwise we run into this situation

```js
const owner = new Owner({ name: 'Alice' })
const pet1 = new Pet({ name: 'Kitty1', owner: owner })
const pet2 = new Pet({ name: 'Kitty2', owner: owner })

console.log(typeof pet1.owner) // 'object'
console.log(typeof pet2.owner) // 'string'
```

File: test/model.populate.test.js [hunk 2]
```diff
@@ -11014,4 +11014,35 @@ describe('model: populate:', function() {
...
+    const Pet = db.model('Pet', petSchema);
+
+    const ownerId = new mongoose.Types.ObjectId();
+    const owner = new Owner({
+      _id: ownerId,
+      name: 'Alice'
+    });
+    await owner.save();
+    const pet = new Pet({ name: 'Kitty', owner: owner });
+    await pet.save();
```
Comment (hasezoey) [inline test/model.populate.test.js:11043]: this could likely be reduced to `.create` calls

**Review by hasezoey — COMMENTED** [review]
LGTM, minor style suggestion and would like to see the question above resolved

File: lib/document.js (hunk 1 above)
Comment (vkarpov15) [reply lib/document.js]: Fixed in 1ad7531, thanks for catching this

File: test/model.populate.test.js (hunk 2 above)
Comment (vkarpov15) [reply test/model.populate.test.js]: Fixed in 1ad7531
