### PR TITLE
always pass unpopulated path to validator closes #8042 closes #8018

### LINKED ISSUE #8018: Populating an id key that doesn't exist anymore in the reference collection (single, not an array) and then saving gives a validation error if the id key is a required value
Hi, I wanted to point out this error I am getting that I think is sort of a bug, since technically we are just executing READ commands on the document(s), and the content changes so that the validation fails.

**What is the current behavior?**
When trying to save a document, after it has been populated on a required key, and the populated key is null because the reference object was not found anymore, trying to save it fails due to a validation error in the populated key being null after the populate.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh8018`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
    const db = await mongoose.connect(connectionString);
    await mongoose.connection.dropDatabase();

    const schema = mongoose.Schema({
        placeHolderKey: {
            type: String,
            default: "TEST"
        }
    });

    const schema2 = mongoose.Schema({
        keyToPopulate: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "SecondaryModel",
            required: true
        }
    });


    const secondaryModelThatIsPopulatedOnTheMainModel = db.model('SecondaryModel', schema);
    const mainModelThatFailsValidation = db.model('MainModelThatFailsRequiredValidation', schema2);

    let secondaryModelObject = await secondaryModelThatIsPopulatedOnTheMainModel.create({placeHolderKey: "TEST"});
    let mainModelObject = await mainModelThatFailsValidation.create({keyToPopulate: secondaryModelObject._id});
    await secondaryModelObject.remove();

    const doc = await mainModelThatFailsValidation.find({_id: mainModelObject._id})
        .populate("keyToPopulate")
        .exec();

    doc[0].save(); //This one normally throws the error

    console.log(doc[0].toObject()); //Removing the `await secondaryModelObject.remove();` will throw no errors
}
```

**What is the expected behavior?**
I think that `populate` shouldn't affect the actual content to the point of making it different from the previous one, since we didn't change anything at all.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.5.2
Node: 8.12.0

### LINKED ISSUE #8042: Always pass unpopulated path to validators
Issues like #8018 make it very confusing to write validation for populated paths.

### PR DESCRIPTION
**Pull request by IslandRhythms**

### CODE REVIEW

File: lib/document.js [hunk 1]
```diff
@@ -2524,9 +2524,8 @@ Document.prototype.$__validate = function(pathsToValidate, options, callback) {
       // If you `populate()` and get back a null value, required validators
       // shouldn't fail (gh-8018). We should always fall back to the populated
       // value.
-      let pop;
-      if (val == null && (pop = _this.populated(path))) {
-        val = pop;
+      if (val == null && _this.populated(path)) {
+        val = _this.depopulate(path);
```
Comment (vkarpov15) [inline lib/document.js:2528]: It looks like this would depopulate the path on the document, rather than depopulating just for the validator. We don't want the depopulate to persist.

File: lib/document.js [hunk 2]
```diff
@@ -2524,9 +2524,8 @@ Document.prototype.$__validate = function(pathsToValidate, options, callback) {
       // If you `populate()` and get back a null value, required validators
       // shouldn't fail (gh-8018). We should always fall back to the populated
       // value.
-      let pop;
-      if (val == null && (pop = _this.populated(path))) {
-        val = pop;
+      if (val == null && _this.populated(path)) {
```
Comment (vkarpov15) [inline lib/document.js:2527]: We should remove this `val == null` check. This `null` check is the crux of this issue: we should always use `val = pop`

**Review by vkarpov15 — CHANGES_REQUESTED** [review]

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
Nice, but can you add a test for this please?

**Comment by IslandRhythms** [comment]
I copied your test from 8018 and just didn't populate it. Not sure if that's how to properly test this fix. I am a bit confused on how to test for passing an unpopulated path to a validator, as I thought that was already default behavior on model creation when you have a field in the document set to `required: true`

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:
