### PR TITLE
enhancement(connection&base): add support for `continueOnError`

### LINKED ISSUE #11039: [SUGGESTION] Make `mongoose.syncIndexes()` and `Connection#syncIndexes()` always successfully fulfilled (error independent)
_Originally posted by @Kamikadze4GAME in https://github.com/Automattic/mongoose/pull/10997#discussion_r755016633_

Maybe is it better to return object, where key is `modelName` and value is result (successful) from `this.model(model).syncIndexes()` or if something went wrong instance of the Error (or MongooseError)?

So the result object will look like (it's just an example):

```js
const syncIndexesResult = await connection.syncIndexes();
// `syncIndexesResult`
{
  model1: ['index-1-1', 'index-1-2'], // this is example of the successful result from `Model.syncIndexes`,
  model2: MongooseError, 
  model3: [...],
}
```

As a result, you could control future actions (ex: show in console list of failed models or manually rerun syncIndexes on failed models).

What do you think?

@vkarpov15 @AbdelrahmanHafez @IslandRhythms 

Ref: #10893, #10997

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
fixes #11039

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -3303,6 +3304,11 @@ declare module 'mongoose' {
       type?: string): this;
   }
 
+  export interface SyncIndexesOptions {
```
Comment (vkarpov15) [inline index.d.ts:3307]: `SyncIndexesOptions` needs to at minimum support the same options as `createIndexes()`. Maybe try `type SyncIndexesOptions = mongodb.CreateIndexesOptions & { continueOnError?: boolean }`?

File: lib/connection.js [hunk 2]
```diff
@@ -1380,11 +1381,37 @@ Connection.prototype.setClient = function setClient(client) {
...
+
+  for (const model of Object.values(this.models)) {
+    try {
+      result[model.modelName] = await model.syncIndexes();
+    } catch (err) {
+      if (!continueOnError) {
+        errorsMap[model.modelName] = err;
+        break;
+      } else {
+        result[model.modelName] = err;
```
Comment (vkarpov15) [inline lib/connection.js:1404]: Nice :+1:

File: lib/connection.js [hunk 3]
```diff
@@ -1380,11 +1381,37 @@ Connection.prototype.setClient = function setClient(client) {
...
+      }
+    }
   }
+
+  if (!continueOnError && Object.keys(errorsMap).length) {
+    const message = Object.values(errorsMap).map(err => err.message).join(' ');
```
Comment (vkarpov15) [inline lib/connection.js:1410]: What do you think about making this formatting consistent with CastErrors, so we do `${key}: ${err.message}` and join with `,`?

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
Couple of minor comments, but :+1: overall

**Review by vkarpov15 — APPROVED** [review]
Nice :+1: merging this into 6.2
