### PR TITLE
fix(cast): make schema-level strictQuery override schema-level strict for query filters

### LINKED ISSUE #12508: Option `strict` is used before Schema and global level `strictQuery`
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.63

### Node.js version

16

### MongoDB server version

4.9.1

### Description

Hello, when strict is set to throw, I cannot set strictQuery to anything else then throw.
On docs, it says
`However, strictQuery is tied to strict by default. This means that, by default, Mongoose will filter out query filter properties that are not in the schema.`
I cannot  untied strictQuery and Query globally on in shcema option, I have to use QueryOption.
This is the expected Behavior ? the doc is unclear.

### Steps to Reproduce

```js
const mongoose = require("mongoose");

mongoose.set("debug", true);
mongoose.set("strictQuery", false);
const options = {
  strict: "throw",
  strictQuery: false
};

const eventSchema = new mongoose.Schema({ time: Date }, options);
const Event = mongoose.model("Event", eventSchema);

async function run() {
  await mongoose.connect("mongodb://localhost:27017");

  // 1. Not working
  await Event.find({ url: "google.com" },
}

run();

```

### Expected Behavior

Should be able to set strictQuery to anything else then throw in schema option or globally not only in query opt

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #12508

**Summary**

Looks like schema-level `strict` overrides schema-level `strictQuery`, which is definitely not something we want given that we want to switch `strictQuery` back to `false` by default.

**Examples**

### CODE REVIEW

File: lib/cast.js [hunk 1]
```diff
@@ -268,8 +268,11 @@ module.exports = function cast(schema, obj, options, context) {
           options.strictQuery :
           'strict' in options ?
             options.strict :
-            'strict' in schema._userProvidedOptions ? schema._userProvidedOptions.strict :
-              schema.options.strictQuery;
+            'strictQuery' in schema._userProvidedOptions ?
```
Comment (AbdelrahmanHafez) [inline lib/cast.js:271]: Nitpick: This seems to be growing so much that it's not easy to understand it at all, I think we should refactor this to an external function that builds the strictQuery value.

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
One refactor suggestion, but otherwise LGTM. Thanks 👍

**Review by IslandRhythms — APPROVED** [review]
LGTM
