### PR TITLE
fix(document): avoid triggering setter when initializing `Model.prototype.collection` to allow defining `collection` as a schema path name

### LINKED ISSUE #13956: How can I use `collection` as schema property name?
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.0

### Node.js version

19.4.0

### MongoDB version

7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

_No response_

### Issue

After doing lots of research, I still can't understand how I can use `collection` as property name in schema because it's a reserved key.

```js
{
    collection : { type : String, required : true }
}
```

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #13956

**Summary**

Right now get the following error when you try to use `collection` as a schema path name:

```
$ node gh-13956.js 
TypeError: Cannot read properties of undefined (reading 'Symbol(mongoose#Document#scope)')
    at Model.set [as collection] (/home/val/Workspace/MongoDB/mongoose/lib/helpers/document/compile.js:205:32)
    at Function.compile (/home/val/Workspace/MongoDB/mongoose/lib/model.js:4776:30)
    at Mongoose._model (/home/val/Workspace/MongoDB/mongoose/lib/index.js:620:27)
    at Mongoose.model (/home/val/Workspace/MongoDB/mongoose/lib/index.js:579:27)
    at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-13956.js:11:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This PR fixes that, you can now use `collection` as a schema name, albeit still with the "`collection` is a reserved schema pathname and may break some functionality." warning.

**Examples**

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -4788,8 +4789,8 @@ Model.compile = function compile(name, schema, collectionName, connection, base)
   applyStaticHooks(model, schema.s.hooks, schema.statics);
 
   model.schema = model.prototype.$__schema;
-  model.collection = model.prototype.collection;
-  model.$__collection = model.collection;
+  model.collection = collection;
+  model.$__collection = collection;
```
Comment (hasezoey) [inline lib/model.js:4793]: i dont quite know why this is set here, but why not also set the symbol?

**Review by hasezoey — APPROVED** [review]
LGTM

File: lib/model.js (hunk 1 above)
Comment (vkarpov15) [reply lib/model.js:4793]: `modelCollectionSymbol` is only set on `Model.prototype`, not `Model`. `modelCollectionSymbol` is necessary for naming conflicts in case both `collection` and `$collection` are schema paths. No risk of name conflicts with schema paths on Model though
