### PR TITLE
fix(errors) - user defines its own r/o err.toJSON

### LINKED ISSUE #8985: crash when user-code defines its own r/o err.toJSON
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
A crash:
```
TypeError: Cannot assign to read only property 'toJSON' of object '[object Object]'
    at Object.<anonymous> (/home/user/exco/web-services/plan-svc/node_modules/mongoose/lib/error/validation.js:76:34)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/exco/web-services/plan-svc/node_modules/mongoose/lib/error/index.js:102:33)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's the simplest one with an observed sensible intent.
```
const safeStringify = require('json-stringify-safe');
Reflect.defineProperty(Error.prototype, 'toJSON', {
  writable: false,
  value() { 
    const { message, stack } = this;
    return Object.entries(this).reduce((json, [k, v]) => {
       json[k] = safeStringify(v);
    }, { message, stack: stack.split('\n') });
  }
});
require('mongoose');
```
However, in real life I'm using a package that does that for me.

**What is the expected behavior?**
Should not throw

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node 10/ node 12, mongodb 3, mongoose:5.9.13

### PR DESCRIPTION
**Pull request by osher**
fixes #8985

When user code defines it's own Error.prototype.toJSON, which is defined as a read-only property - the fixed line crashes.
It happens specificly because of the old-school `Object.create(prototype)` thing.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. The two fields below are mandatory.

If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.pug` file or test case in the `test/docs` directory.

**Summary**

fixes #8985

**Examples**

Added tests

### CODE REVIEW

File: lib/error/validation.js [hunk 1]
```diff
@@ -72,10 +72,14 @@ if (util.inspect.custom) {
 /*!
  * Helper for JSON.stringify
  */
-
-ValidationError.prototype.toJSON = function() {
-  return Object.assign({}, this, { message: this.message });
-};
+Object.defineProperty(ValidationError.prototype, 'toJSON', {
+  enumerable: false,
+  writabe: false,
```
Comment (vkarpov15) [inline lib/error/validation.js:77]: Typo, this should be `writable`.
