### PR TITLE
fix(model): ensure $isDeleted is set after calling `doc.deleteOne()` successfully

### LINKED ISSUE #15858: The $isDeleted is not set automatically as the documentation states.
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.20.1

### Node.js version

24.5.0

### MongoDB server version

8.0.3

### Typescript version (if applicable)

5.9.3

### Description

As the [documentation](https://mongoosejs.com/docs/8.x/docs/api/document.html#Document.prototype.$isDeleted()) says:

> The Model.prototype.deleteOne() method sets $isDeleted if the delete operation succeeded.

But it doesn't. The `$isDeleted()` method returns `false` after calling the `deleteOne()` method and the document has been deleted successfully.

The example given in documentation cannot be run because the product variable cannot be redeclared.

> TS2451: Cannot redeclare block-scoped variable `product`

The `deleteOne()` method returns [DeleteResult](https://github.com/mongodb/node-mongodb-native/blob/a96fa26dea3060828af747f0f2974229018de730/src/operations/delete.ts#L24-L29) not the document itself.

The way I achived the expected result is:

```typescript
await product.deleteOne();
product.$isDeleted(true);
```
And after I can check whether the document has been deleted or not.

### Steps to Reproduce

Follow the example on the  [documentation](https://mongoosejs.com/docs/8.x/docs/api/document.html#Document.prototype.$isDeleted())  page.

### Expected Behavior

The `$isDeleted()` method returns `true` after calling `deleteOne()` on the document and it has been successfully deleted from the database.

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #15858

**Summary**

Using `query.transform()` instead of `query.post()` because Mongoose doesn't pass the result to `query.post()`, and adding the result to `query.post()` would be backwards breaking for cb-based post hooks.

**Examples**

### CODE REVIEW

**Review by hasezoey — COMMENTED** [review]
LGTM, aside from what copilot brought up about the issue id in test name

File: lib/model.js [hunk 1]
```diff
@@ -829,6 +829,12 @@ Model.prototype.deleteOne = function deleteOne(options) {
   query.post(function queryPostDeleteOne(cb) {
     self.constructor._middleware.execPost('deleteOne', self, [self], {}, cb);
   });
+  query.transform(function setIsDeleted(result) {
+    if (result && result.deletedCount != null && result.deletedCount > 0) {
```
Comment (AbdelrahmanHafez) [inline lib/model.js]: Nitpicky suggestion:
```suggestion
    if (result?.deletedCount > 0) {
```

Take it with a grain of salt for now, will be looking more into the benchmarks of optional chaining later on my PR 👍

**Comment by Neha-Sharmaaa** [comment]
Implemented in #16137

`query.post()` middleware now receives the query result as the first parameter.

**Usage:**
```js
query.post(function(result) {
  if (result.deletedCount > 0) {
    // Handle successful delete
  }
});
```

**Supported signatures:**
- `query.post(function() {})` - backward compatible, no params
- `query.post(function(result) {})` - receives result
- `query.post(function(result, next) {})` - receives result + next for async

Works with find(), findOne(), updateOne(), deleteOne(), and other query operations. Fully backward compatible.
