### PR TITLE
fix(model): use duck-typing with version check to validate the argument to useConnection() is actually a connection

### LINKED ISSUE #16098: `Model.useConnection()` lacks validation for Connection instance, causing silent state corruption
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

9.3.0

### Node.js version

20.x

### MongoDB server version

7.x

### Typescript version (if applicable)

_No response_

### Description

The guard only checks `if (!connection)`, but passes any truthy value through. Passing a plain object, a string, or an unrelated class instance causes confusing downstream errors when `connection.collection(...)` or `connection.models[...]` is accessed.

### Steps to Reproduce

```javascript
const Model = mongoose.model('Test', new Schema({ name: String }));
// Silently succeeds but corrupts state
Model.useConnection({ not: 'a connection' }); 
// Downstream error
try {
  await Model.findOne();
} catch (err) {
  console.log(err); // TypeError: connection.collection is not a function
}

### Expected Behavior

`Model.useConnection()` should throw a `TypeError` if the provided argument is not an instance of `mongoose.Connection`

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #16098

**Summary**

Throw an error if the argument to `useConnection()` doesn't have `model()` and `collection()` functions - sufficient to avoid many common potentially incorrect arguments. Also check that the version is an exact match. This avoids erroring out in the case of multiple Mongoose modules presuming the versions line up exactly. We do not want to support mixed versions - using a connection from version 8.1.4 with a model from version 8.2.1 is not something we can reasonably write tests for.

**Examples**

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -189,8 +189,11 @@ Model.prototype.db;
  */
 
 Model.useConnection = function useConnection(connection) {
-  if (!connection) {
-    throw new MongooseError('Please provide a connection.');
+  if (!connection || typeof connection.model !== 'function' || typeof connection.collection !== 'function') {
```
Comment (AbdelrahmanHafez) [inline lib/model.js]:
```suggestion
  if (typeof connection?.model !== 'function' || typeof connection.collection !== 'function') {
```

**Review by AbdelrahmanHafez — APPROVED** [review]

File: lib/model.js (hunk 1 above)
Comment (hasezoey) [reply lib/model.js]:
```suggestion
  if (typeof connection?.model !== 'function' || typeof connection?.collection !== 'function') {
```

~~As this is a OR, it may error on the second condition~~

Nevermind, forgot `(typeof undefined !== 'function') === true`.

File: test/model.test.js [hunk 2]
```diff
@@ -9173,9 +9173,42 @@ describe('Model', function() {
...
-      assert.throws(() => {
-        Model.useConnection();
-      }, { message: 'Please provide a connection.' });
+      assert.throws(
+        () => Model.useConnection(),
+        { name: 'MongooseError', message: '`useConnection()` requires a Mongoose connection.' }
+      );
+    });
+
+    it('should throw a MongooseError if a non-connection object is passed (gh-16098)', async function() {
```
Comment (hasezoey) [inline test/model.test.js]:
```suggestion
    it('should throw a MongooseError if a non-connection object is passed (gh-16098)', function() {
```

File: test/model.test.js [hunk 3]
```diff
@@ -9173,9 +9173,42 @@ describe('Model', function() {
...
+      const schema = new mongoose.Schema({ name: String });
+      const Model = db.model('Test', schema);
+      assert.throws(
+        () => Model.useConnection({}),
+        { name: 'MongooseError', message: '`useConnection()` requires a Mongoose connection.' }
+      );
+    });
+
+    it('should throw a MongooseError if null is passed (gh-16098)', async function() {
```
Comment (hasezoey) [inline test/model.test.js]:
```suggestion
    it('should throw a MongooseError if null is passed (gh-16098)', function() {
```

File: test/model.test.js [hunk 4]
```diff
@@ -9173,9 +9173,42 @@ describe('Model', function() {
...
+      const schema = new mongoose.Schema({ name: String });
+      const Model = db.model('Test', schema);
+      assert.throws(
+        () => Model.useConnection(null),
+        { name: 'MongooseError', message: '`useConnection()` requires a Mongoose connection.' }
+      );
+    });
+
+    it('should throw a MongooseError if mismatched Mongoose version (gh-16098)', async function() {
```
Comment (hasezoey) [inline test/model.test.js]:
```suggestion
    it('should throw a MongooseError if mismatched Mongoose version (gh-16098)', function() {
```

File: lib/model.js [hunk 5]
```diff
@@ -189,8 +189,11 @@ Model.prototype.db;
...
+    throw new MongooseError('`useConnection()` requires a Mongoose connection.');
+  }
+  if (this.db.base?.version && this.db.base?.version !== connection.base?.version) {
+    throw new MongooseError('The connection passed to `useConnection()` has a different version of Mongoose than the model you are using.');
```
Comment (hasezoey) [inline lib/model.js]: For clarity, this message could include both versions used.

**Review by hasezoey — APPROVED** [review]
LGTM, minor nitpicks.
