### PR TITLE
fix(query): Query#select({ field: false }) should not overwrite schema selection options

### LINKED ISSUE #8923: Model doesn't respect its subschema {select: false|true} properties
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

Model A has a subschema which it has a field marked as `select: false`. Model A projection doesn't respect its subschema and returns the whole subschema.

**If the current behavior is a bug, please provide the steps to reproduce.**

```node
// SubSchema
{
  firstName: {type: String, select: false},
  lastName: {type: String}
}

// Model A
{
  username: {type: String},
  subSchema: {type: SubSchema}
}

// Find one along with a projection
ModelA.findById(id, {username: false}).exec();

// Expected result > { subSchema: { lastName: 'Lenon' } }
// Actual result > { subSchema: { firstName: 'John', lastName: 'Lenon' } }
```

**What is the expected behavior?**

From the sample above, returns `{ subSchema: { lastName: 'Lenon' } }`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

`MongoDB: 4.2.5`
`Mongoose: 5.9.11`
`Node.js: 12.10.0`

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
fixes #8923

### CODE REVIEW

**Comment by AbdelrahmanHafez** [comment]
I usually try to start a PR with a failing test, then wait till CI finishes up, then push the fix.

Apparently doing both commits too quickly causes the CI to use the commit with (test+fix) and falsely pass. Therefore the 3rd, and 4th commit.

File: lib/queryhelpers.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ exports.applyPaths = function applyPaths(fields, schema) {
       if (!isDefiningProjection(field)) {
         continue;
       }
-      exclude = field === 0;
+      exclude = field === 0 || field === false;
```
Comment (vkarpov15) [inline lib/queryhelpers.js:138]: I think it would be better for this to be `exclude = !field`. Better to use [falsy](https://masteringjs.io/tutorials/fundamentals/falsy) rather than hard coding `0` and `false` as the allowed values while leaving `0n` as equivalent to `true`.

**Comment by vkarpov15** [comment]
I'd err on the side of not putting in an extra commit to trigger the test failure. Separate test and fix commits are fine though.

File: lib/queryhelpers.js (hunk 1 above)
Comment (AbdelrahmanHafez) [reply lib/queryhelpers.js:138]: Sounds reasonable.
