### PR TITLE
types: automatically infer discriminator type

### LINKED ISSUE #15535: Type inference for discriminator models are broken
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.16.2

### Node.js version

22.13.1

### MongoDB server version

8.0.4

### Typescript version (if applicable)

5.7.3

### Description

Discriminator models only have the `_id` and `__v` properties associated with their typings. All type inferences from its schema definition or the schema definition of its parent are lost.

### Steps to Reproduce

```javascript
const ParentSchema = new Schema({
  field1: {
    type: String,
    require: true,
  },
  field2: Number,
}, {
  discriminatorKey: 'field1',
})

const ParentModel = mongoose.model('Parent', ParentSchema)

const ChildSchema = new Schema({
  field3: String,
})

const ChildModel = ParentModel.discriminator('child', ChildSchema)
```

Typescript shows the fields associated with `ChildModel` and any documents created via `ChildModel` are just `_id` and `__v` when they should include `field1`, `field2`, and `field3`.

### Expected Behavior

Correct type inference should show that fields associated with `ChildModel` and any documents created via `ChildModel` should include `field1`, `field2`, and `field3`.

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #15535

**Summary**

Add a `discriminator()` function override that automatically infers the returned schema type from TypeScript types by combining the schema generics.

**Examples**

### CODE REVIEW

File: types/models.d.ts [hunk 1]
```diff
@@ -419,6 +418,33 @@ declare module 'mongoose' {
       TInstanceMethods & TVirtuals
     >;
 
+    /** Adds a discriminator type. */
+    discriminator<TDiscriminatorSchema extends Schema<any>>(
+      name: string,
```
Comment (hasezoey) [inline types/models.d.ts]: Just to confirm, this shouldnt also be `| number`?

**Review by hasezoey — APPROVED** [review]

**Comment by vkarpov15** [comment]
@hasezoey can you take another look? I did some performance refactoring to reduce and offset the additional instantiations introduced by this PR.

**Review by hasezoey — APPROVED** [review]
Still looks good to me.
