### PR TITLE
fixes #6477 prevent default falses from being skipped by $__dirty

### LINKED ISSUE #6477: [Bug] Inconsistent Boolean Default Value on Save
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Given a doc that was created before a new boolean schema field was added, if the boolean schema field is set to `default: false`, it will not be set to false. However, if it is `default: true`, it will be set to true. This is probably clearer looking at the example.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// index.js
const mongoose = require('mongoose');
// Import User Schema
require('./user');

mongoose.connect('mongodb://localhost:27017/mongo-default-bug');

const User = mongoose.model('User');

const newUser = new User({
  otherVal: 99,
  defaultValT: undefined,
  defaultValF: undefined,
});

// Save the new user doc
newUser.save().then(() => {
  // Remove defaultValT, defaultValF to simulate this is an old doc before
  // new schema with `defaultValT and `defaultValF` were added in as fields.
  User.collection.update(
    {}, {$unset: {defaultValT: true, defaultValF: true}},
    {multi: true, safe: true},
    () => {
      // Update the user doc
      User.findOne({}).then(user => {
        user.otherVal = 9999;
        user.save();
        console.log(user);
      })
    }
  );
});
```
```javascript
// user.js
const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * User Schema
 */
const UserSchema = new Schema({
  defaultValT: { type: Boolean, default: true },
  defaultValF: { type: Boolean, default: false },
  otherVal: 0,
});

mongoose.model('User', UserSchema);
```

The console.log statement will print:
```
{ defaultValT: true,
  defaultValF: false,
  _id: 5afc7908d5b4056e35502493,
  otherVal: 9999,
  __v: 0 }
```

However looking at the db from mongo shell and mongo compass db:
```
{
	"_id" : ObjectId("5afc7908d5b4056e35502493"),
	"otherVal" : 9999,
	"__v" : 0,
	"defaultValT" : true
}
```

**What is the expected behavior?**

Honestly I'm not sure, the [default value docs](http://mongoosejs.com/docs/defaults.html) seem to state that *none* of the fields should be updated to the default value since default only applies on insert, unless `setDefaultsOnInsert`. But it seems like it's being applied anyways, no idea why, but it should at least be consistent between `default: true` and `default: false`.

**Please mention your node.js, mongoose and MongoDB version.**

```
node --version
v8.4.0
mongoose@5.1.1
MongoDB server version: 3.6.2
```

### PR DESCRIPTION
**Pull request by lineus**
As demonstrated in #6477, a document returned from a query, with an unset field that defaults to false, subsequently saved would not add the default to the document. This change aligns the behavior with other path defaults.

all current tests pass, made a failing test, then made it pass.
```
mongoose>: npm test

> mongoose@5.1.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js


 You're not testing shards!
 Please set the MONGOOSE_SHARD_TEST_URI env variable.
 e.g: `mongodb://localhost:27017/database
 Sharding must already be enabled on your database


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,,,,,,,,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  1916 passing (25s)
  9 pending

mongoose>:
```

### Output of 6477.js before change:
```
issues: ./6477.js
5.1.1: f: failed to set f = false on save()
issues: 
```
### Output of 6477.js after change:
```
issues: ./6477.js
5.1.2-pre:
issues:
```

### CODE REVIEW

**Comment by lineus** [comment]
not sure why this just dawned on me, but I think the test shouldn't be in model.test.js :-1. I'm looking at fixing this now.

File: lib/document.js [hunk 1]
```diff
@@ -2003,7 +2003,8 @@ Document.prototype.$__dirty = function() {
   // gh-2558: if we had to set a default and the value is not undefined,
   // we have to save as well
   all = all.concat(this.$__.activePaths.map('default', function(path) {
-    if (path === '_id' || !_this.getValue(path)) {
+    var pType = typeof _this.getValue(path);
+    if (path === '_id' || (!_this.getValue(path) && pType !== 'boolean')) {
```
Comment (vkarpov15) [inline lib/document.js]: This check is a little odd, and will still mess up with empty strings `''` because empty string is falsy. Can we change this to `|| _this.getValue(path) == null`?

Comment (lineus) [reply lib/document.js]: Odd indeed. fixed and test added for empty strings just in case I try to break it again 😀
