### PR TITLE
types: make SchemaType static `setters` property accessible in TypeScript

### LINKED ISSUE #14879: Setters property of schema types not available in TS declarations
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.1

### Node.js version

20.13.1

### MongoDB server version

7.0.8

### Typescript version (if applicable)

5.5.2

### Description

In #13538 , a new static `setters` property was added to several schema type classes as well as an instance `setters` property to the base `SchemaType` class. These properties are not available in the TS declaration files, so accessing the setters property is issuing a type error.

image

### Steps to Reproduce

```ts
mongoose.Schema.Types.String.setters.push((val?: unknown) => val);
```
Type error will occur on the access of the missing `setters` property.

### Expected Behavior

The `setters` property should allow pushing a setter function without type error.

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #14879

**Summary**

There are places in the docs where we recommend pushing default setters to schematypes like `mongoose.Schema.String.setters.push(fn)`, but TypeScript types currently don't support that.

**Examples**

### CODE REVIEW

File: types/schematypes.d.ts [hunk 1]
```diff
@@ -216,6 +216,9 @@ declare module 'mongoose' {
     /** Attaches a getter for all instances of this schema type. */
     static get(getter: (value: any) => any): void;
 
+    /** Array containing default setters for all instances of this SchemaType */
+    static setters: Function[];
```
Comment (hasezoey) [inline types/schematypes.d.ts:220]:
```suggestion
    static setters: ((val?: unknown) => unknown)[];
```

i think it is better with known arguments, unless there are more arguments?

**Review by hasezoey — APPROVED** [review]
