### PR TITLE
fix(document): apply setters on resulting value when calling Document.prototype.$inc()

### LINKED ISSUE #13158: Mongoose schema setter not being called when using $inc
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^6.9.0

### Node.js version

18.12.1

### MongoDB version

5.0.15

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I run in a problem. I have defined a setter in my model:

```js
const userSchema = new mongoose.Schema({
    money: {
        balance: {
            type: Number,
            set: (v) => Number(v)?.toFixed(4),
            default: 0,
        },
    },
});
```

When I try increasing balance of a user, it does format the number when the value is positive but sometimes not when its negative, which is weird.

```js
await User.findByIdAndUpdate(userId, {
        $inc: {
            'money.balance': earnings,
        },
    },
    { runValidators: true }
);
```

Thanks for helping me

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #13158

**Summary**

Document.prototype.$inc() doesn't call setters right now, which is a little strange given that `findOneAndUpdate()` with `$inc` does call setters.

The biggest wrinkle here is that we're calling setters on the _resulting value_, not the value passed in to `$inc`. So `$inc('balance', 4)` will call setters with `balance = 6 + 4` if `balance` was originally 6. I think this is slightly better because setters are often used for rounding, and we want to make sure devs that are using `$inc()` instead of `+=` don't run into unexpected binary floating point precision issues.

**Examples**

### CODE REVIEW

File: lib/document.js [hunk 1]
```diff
@@ -1783,18 +1783,22 @@ Document.prototype.$inc = function $inc(path, val) {
     return this;
   }
 
+  const currentValue = this.$__getValue(path) || 0;
+  let valToSet = currentValue + val;
```
Comment (hasezoey) [inline lib/document.js:1787]: is this correct to not have `castNumber(val)` too? (like in the try block)

Comment (vkarpov15) [reply lib/document.js]: You're right. My assumption was that setting the invalid value if casting fails, we should still set the value. But that isn't correct. For example, below script still prints 42:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1/mongoose_test');
  const Test = mongoose.model('Test', mongoose.Schema({ num: Number }));

  const doc = new Test({ num: 42 });
  doc.num = 'abc';
  console.log(doc.num);
}
```

Thanks for calling that out. Can you re-review please?

File: test/document.test.js [hunk 2]
```diff
@@ -11649,6 +11649,51 @@ describe('document', function() {
...
+        doc.$inc('counter', 1.14159);
+        assert.deepEqual(called, [2, 3.14159]);
+        assert.equal(doc.counter, 3.14);
+        await doc.save();
+
+        const res = await Test2.findById(doc);
+        assert.equal(res.counter, 3.14);
+      });
+
+      it('sets value even if setter fails (gh-13158)', async function() {
```
Comment (hasezoey) [inline test/document.test.js:11672]: i think this title now needs to be changed, because from my understanding it does not actually change the value anymore on fail

**Review by IslandRhythms — APPROVED** [review]
I think hasezoey is right, otherwise LGTM
