### PR TITLE
fix(model): avoid deleting shared schema methods in fix for #12254

### LINKED ISSUE #12423: PR #12254 introduced bug: Methods defined in shared schemas get removed
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.5

### Node.js version

16.6

### MongoDB server version

6.0.1

### Description

PR https://github.com/Automattic/mongoose/issues/12254 introduces a bug 
where instance methods defined in shared schema get deleted. 

Problem located in line 38 in file
mongoose/lib/helpers/model/applyMethods.js

Commit
https://github.com/Automattic/mongoose/commit/9fbf92c3a8c6f0717beb404f4020832aafe93589#diff-9de3851c9d06234f6bef122196730d35ce2dc68fc2b609824b1676194608e4fb

### Steps to Reproduce

1. Install mongoose 6.5.5
2. Run this bug demo script:

```js
const mongoose = require('mongoose')
mongoose.set('debug', true)

const sharedSubSchema = new mongoose.Schema({
  name: {
    type: String
  }
})

sharedSubSchema.methods.sharedSubSchemaMethod = function () {
  console.log('sharedSubSchemaMethod called')
}

const mainDocumentSchema = new mongoose.Schema({
  subdocuments: {
    type: [sharedSubSchema],
    required: true
  }
})
const MainDocument = mongoose.model('MainDocument', mainDocumentSchema)

const secondaryDocumentSchema = new mongoose.Schema({
  subdocuments: {
    type: [sharedSubSchema],
    required: true
  }
})
const SecondaryDocument = mongoose.model('SecondaryDocument', secondaryDocumentSchema)

const mainDoc = new MainDocument({
  subdocuments: [
    {
      name: 'one'
    }
  ]
})

const secondaryDoc = new SecondaryDocument({
  subdocuments: [
    {
      name: 'secondary'
    }
  ]
})

console.log(mainDoc.subdocuments[0].sharedSubSchemaMethod)
console.log(secondaryDoc.subdocuments[0].sharedSubSchemaMethod)
```

### Expected Behavior

Sub-Document method should be defined on both models, not only one.

Buggy output mongoosejs 6.5.5
[Function (anonymous)]
undefined

Correct output mongoosejs 6.5.4
[Function (anonymous)]
[Function (anonymous)]

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #12423

**Summary**

In #12423 it looks like we now delete shared schema methods, which is definitely unintentional. We should only delete schema methods that exactly match methods on the Mongoose `Model` class prototype.

**Examples**

### CODE REVIEW

File: lib/helpers/model/applyMethods.js [hunk 1]
```diff
@@ -34,7 +36,8 @@ module.exports = function applyMethods(model, schema) {
     // Avoid making custom methods if user sets a method to itself, e.g.
     // `schema.method(save, Document.prototype.save)`. Can happen when
```
Comment (AbdelrahmanHafez) [inline lib/helpers/model/applyMethods.js:37]:
```suggestion
    // `schema.method('save', Document.prototype.save)`. Can happen when
```

**Review by AbdelrahmanHafez — APPROVED** [review]
LGTM, thanks 👍

**Review by Uzlopak — APPROVED** [review]
