### PR TITLE
fixes #6726 pass Model instance as context to applyGetters

### LINKED ISSUE #6726: Inconsistent `this` in getters of schema types
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
As of `5.2.3`, _getters_ of schema types have inconsistent `this` context.

Before that release we used to assume that `this` would be the instance of `Model`. Now, when a path has a getter and is populated by a `ref`, at some point that getter is invoked with `this` being the plain object `doc`.

I couldn't found in the documentation that the old behavior is a public API, but having two calling contexts for getters is a bit messy.

Unfortunately my application depended on the old behavior. :disappointed:

I've found that this issue was introduced here: https://github.com/Automattic/mongoose/pull/6702/files#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR3947

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const BarSchema = new mongoose.Schema({});
const Bar = mongoose.model('Bar', BarSchema);

const FooSchema = new mongoose.Schema({
  bar: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Bar',
    get(value) {
      console.log(this.constructor.name); // sometimes it prints `model`, sometimes `Object` 
      return value;
    },
  },
});
const Foo = mongoose.model('Foo', FooSchema);

const bar = new Bar();
await bar.save();

const foo = new Foo({bar: bar});
await foo.save();

const fooWithPopulate = await Foo.find({_id: foo._id}).populate('bar');
fooWithPopulate.bar;
```

**What is the expected behavior?**
`this` in a getter function should always be the instance of `Model`.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v10.6.0
mongoose: v5.2.3
MongoDB: v3.6.1

### PR DESCRIPTION
**Pull request by lineus**
#6726 shows that the value of `this` in the path getter from #6702 isn't a Model instance. I couldn't find precedent for calling `hydrate` in this context, but this was best solution I could come up with. I'll sleep on it and take another look in the morning. If this isn't as off the wall as it feels....

I added a failing test, made it pass, all current tests pass.

```
mongoose>: npm test -- -g gh-6726

> mongoose@5.2.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6726"


 You're not testing shards!
 Please set the MONGOOSE_SHARD_TEST_URI env variable.
 e.g: `mongodb://localhost:27017/database
 Sharding must already be enabled on your database

(node:20855) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

  !

  0 passing (593ms)
  1 failing

  1) model: populate:
       lean + deep populate (gh-6498)
         passes scope as Model instance (gh-6726):

      Uncaught AssertionError [ERR_ASSERTION]: 'Object' === 'model'
      + expected - actual

      -Object
      +model

      at Object.get (test/model.populate.test.js:7142:20)
      at ObjectId.SchemaType.applyGetters (lib/schematype.js:747:20)
      at getModelsMapForPopulate (lib/model.js:3951:28)
      at populate (lib/model.js:3473:21)
      at _populate (lib/model.js:3443:5)
      at utils.promiseOrCallback.cb (lib/model.js:3416:5)
      at Object.promiseOrCallback (lib/utils.js:222:14)
      at Function.Model.populate (lib/model.js:3415:16)
      at model.Query.Query._completeOne (lib/query.js:1727:9)
      at Immediate.Query.base.findOne.call (lib/query.js:1764:10)
      at Immediate._onImmediate (node_modules/mquery/lib/utils.js:119:16)



npm ERR! Test failed.  See above for more details.
mongoose>: npm test -- -g gh-6726

> mongoose@5.2.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6726"


 You're not testing shards!
 Please set the MONGOOSE_SHARD_TEST_URI env variable.
 e.g: `mongodb://localhost:27017/database
 Sharding must already be enabled on your database

(node:20898) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

  !

  0 passing (552ms)
  1 failing

  1) model: populate:
       lean + deep populate (gh-6498)
         passes scope as Model instance (gh-6726):

      AssertionError [ERR_ASSERTION]: 'Max' === 'Min'
      + expected - actual

      -Max
      +Min

      at test/model.populate.test.js:7154:16
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.
mongoose>: npm test -- -g gh-6726

> mongoose@5.2.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6726"


 You're not testing shards!
 Please set the MONGOOSE_SHARD_TEST_URI env variable.
 e.g: `mongodb://localhost:27017/database
 Sharding must already be enabled on your database

(node:20945) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

  ․

  1 passing (550ms)

mongoose>: npm test

> mongoose@5.2.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js


 You're not testing shards!
 Please set the MONGOOSE_SHARD_TEST_URI env variable.
 e.g: `mongodb://localhost:27017/database
 Sharding must already be enabled on your database

(node:20973) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․(node:20973) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․,,․․․․․․․․․․․․․․․․․․․․

  1990 passing (33s)
  4 pending

mongoose>: 
```
### 6726.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;


const BarSchema = new mongoose.Schema({});
const Bar = mongoose.model('Bar', BarSchema);

const FooSchema = new mongoose.Schema({
  bar: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Bar',
    get(value) {
      console.log(this.constructor.name); // sometimes it prints `model`, sometimes `Object` 
      return value;
    },
  },
});

const Foo = mongoose.model('Foo', FooSchema);
const bar = new Bar();
const foo = new Foo({ bar: bar });

async function run() {
  await bar.save();
  await foo.save();
  const fooWithPopulate = await Foo.find({ _id: foo._id }).populate('bar');
  fooWithPopulate.bar;
  return conn.close();
}

run();
```
### The output of 6726.js before change:
```
issues: ./6726.js
model
model
Object
issues:
```

### The output of 6726.js after change:
```
issues: ./6726.js
model
model
model
issues:
```

### CODE REVIEW

**Comment by lineus** [comment]
@vkarpov15, If there's a better way to handle this I can't see it given the context at this part of the code. The only other solution that I could think of would be to manually do all or at least some of what hydrate already does, but I think some of the magic hydrate provides here is useful, in particular the skipDefaults? 

Let me know if there's something obvious I'm missing. Thanks!

File: lib/model.js [hunk 1]
```diff
@@ -3948,7 +3948,7 @@ function getModelsMapForPopulate(model, docs, options) {
     let ret;
 
     if (localFieldGetters.length) {
-      ret = localFieldPath.applyGetters(doc[localField], doc);
+      ret = localFieldPath.applyGetters(doc[localField], model.hydrate(doc));
```
Comment (vkarpov15) [inline lib/model.js]: Only suggestion would be to check if `doc` is already hydrated before hydrating. Generally we use `doc.$__ != null` to check whether the doc is already hydrated.

**Comment by vkarpov15** [comment]
Looks good modulo the one comment I have. We don't use `hydrate()` internally but we should, just the internal logic for `hydrate()` is much older than `hydrate()`, and we haven't had time to refactor.
