### PR TITLE
fix(populate): call setter on virtual populated path with populated doc instead of undefined

### LINKED ISSUE #14285: virtual setter called with value undefined on populate
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.0

### Node.js version

18.18.0

### MongoDB server version

7.0.5

### Typescript version (if applicable)

_No response_

### Description

Mongoose populates the virtual internally (`set()` is never called with the populated value), but additionally calls its setter function with the value `undefined`. This can lead to bad, unexpected side effects.

I'm not sure whether that is expected behavior, but if so, please advise on how we should implement the below use case.

### Steps to Reproduce

Example script which outputs a person with `userId: null` and `userType: null`.

```js
const mongoose = require('mongoose');
const uri = "mongodb://mongo1:27017/test";

async function run() {
    try {
        await mongoose.connect(uri);
        console.log("connected");

        const Schema = mongoose.Schema;
        const ObjectId = Schema.ObjectId;

        const userSchema = new Schema({
            email: String,
            name: "String",
        });

        const User = mongoose.model('User', userSchema);

        const user = await User.updateOne({
            email: "admin@example.com",
        }, {
            email: "admin@example.com",
            name: "Admin",
        }, {
            upsert: true,
        });

        const personSchema = new Schema({
            userId: ObjectId,
            userType: String,
        });

        personSchema.virtual('user', {
            ref() {
                return this.userType;
            },
            localField: "userId",
            foreignField: "_id",
            justOne: true,
        })
        .set(function (user) {
            console.log("set user:", user);
            if (user) {
                this.userId = user._id;
                this.userType = toModelName(user);
            } else {
                this.userId = null;
                this.userType = null;
            }
        });

        personSchema.pre("findOne", function () {
            this.populate("user");
        });

        const Person = mongoose.model('Person', personSchema);

        const fetchedUser = await User.findOne({ email: "admin@example.com" })

        const person = new Person({
            userId: fetchedUser._id,
            userType: "User",
        });

        await person.save();

        const fetchedPerson = await Person.findOne({ _id: person._id });

        console.log("person fetched:", fetchedPerson.toJSON({ virtuals: true }));
    } catch (e) {
        console.error(e);
    } finally {
        await mongoose.disconnect();
    }
}

run().catch(console.dir).then(() => console.log("Done"));
```

### Expected Behavior

The populated field (i.e. `person`) to be populated and the setter not to be called or called with the value that was populated.

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #14285

**Summary**

Looks like the virtual populate setter doesn't correctly return the populated doc, this PR fixes that. Also did a quick bit of refactor to make it so that we have less populate logic in `lib/schema.js`.

**Examples**

### CODE REVIEW

File: lib/helpers/populate/setPopulatedVirtualValue.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
+'use strict';
+
+module.exports = function setPopulatedVirtualValue(populatedVirtuals, name, v, options) {
```
Comment (hasezoey) [inline lib/helpers/populate/setPopulatedVirtualValue.js:3]: maybe consider adding some jsdoc (at least types and descriptions of the parameters)

**Review by hasezoey — APPROVED** [review]
Looks good to me, aside from some jsdoc

**Review by hasezoey — APPROVED** [review]
