### PR TITLE
docs: fix inverted explanation of `justOne` option for populate

### LINKED ISSUE #12599: The property justOne in PopulateOptions states an error
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

16.x

### MongoDB server version

4.9.1

### Typescript version (if applicable)

^4.5.3

### Description

The property justOne in PopulateOptions states an error

```   
    /**
     * If true Mongoose will always set `path` to an array, if false Mongoose will
     * always set `path` to a document. Inferred from schema by default.
     */
     justOne?: boolean;
```
When justOne is set  false, the result is an array， true will retrun  a document.

### Steps to Reproduce

set justOne:false and  justOne:true , 
the result does not match the document description

### Expected Behavior

The property justOne in PopulateOptions states an error ？
Determine if it is a bug, hope to update the documentation and code source code

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #12599

**Summary**

In a couple of places our description of the `justOne` flag is flipped. This PR fixes that.

**Examples**

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -4556,7 +4556,7 @@ Model.validate = function validate(obj, pathsToValidate, context, callback) {
  * - match: optional query conditions to match
  * - model: optional name of the model to use for population
  * - options: optional query options like sort, limit, etc
- * - justOne: optional boolean, if true Mongoose will always set `path` to an array. Inferred from schema by default.
+ * - justOne: optional boolean, if true Mongoose will always set `path` to a document or `null`. If false, Mongoose will always set `path` to a potentially empty array. Inferred from schema by default.
```
Comment (AbdelrahmanHafez) [inline lib/model.js:4559]: `"to a potentially empty array"` makes me question what that means. Is it a document/null if it's an id, null if not found., or an array (empty if none found) of documents if the path is an array of ids?

If my understanding is correct, I think we should be a bit more verbose in favor of explaining in more detail how it works.

**Review by AbdelrahmanHafez — APPROVED** [review]
LGTM, thanks. 👍

**Review by Uzlopak — APPROVED** [review]

**Review by hasezoey — APPROVED** [review]
